package-lock.json, package.json
Due to Lerna not being able to infer unreferenced packages, they need to be added manually.
=> KUBELT > CHORE (Sanity): Fix unmet dependency

README.md, www/config/_default/params.toml, www/layouts/index.html
Update the base README file with clear instructions.
Rendering readme in branch on github
=> chore(docs): readme updates

www/content/en/docs/basics/how-it-works.md, www/content/en/docs/basics/introduction.md, www/content/en/docs/basics/why-kubelt.md
Read through the docs and found sentences that needed minor tweaks.
=> chore(docs): Fix small grammatical errors in docs

README.md, dapp/README.md, packages/ddt/README.md, packages/kbt/README.md, packages/p2p/README.md, packages/sanity-plugin-kubelt/README.md, packages/sdk-clj/README.md, packages/sdk-cljs/README.md, packages/sdk-js/README.md, packages/sdk-web/README.md
Change status to version in docs badge
Github Render
=> chore(docs): docs version

.github/workflows/ref-docs.yaml, shadow-cljs.edn
Update some dependencies:
- in a GitHub workflow
- in `shadow-cljs.edn`
=> chore: update dependencies

packages/sanity-plugin-kubelt/src/domain/kubeltWallet.ts
Checksum for client account inside the sanity plugin. For proper integration with auth flow.
Closes #289
=> FEAT(Sanity): Add checksum to client account computation

.github/workflows/develop.yaml, .github/workflows/next.yaml, .github/workflows/release.yaml
With the recent mothballing of some code we should no longer require this dependency to be installed in the build pipeline.
=> chore(build): remove install of libsystemd-dev

www/layouts/showcase/single.html
Fix the rendering of taxonomies on single template in showcase.
=> fix(www): showcase taxonomies

README.md
=> chore(readme): fix directory delimiter position

dapp/README.md
From dev/cljs/user.cljs  to dev/user.cljs
=> Fix dev/user.cljs path

dapp/src/dapp/components/login.cljs, dapp/src/dapp/pages/dashboard.cljs, dapp/src/dapp/routes.cljs, dapp/src/dapp/utils.cljs, dapp/src/dapp/wallet.cljs
updating debug info to use timbre logging 
Closes # (issue)
=> feat(dapp) use timbre for logging

packages/sdk-js/__tests__/api-v1.js, src/main/com/kubelt/ddt/cmds/sdk.cljs, src/main/com/kubelt/ddt/cmds/sdk/core/authenticate.cljs, src/main/com/kubelt/ddt/cmds/sdk/options.cljs, src/main/com/kubelt/ddt/cmds/wallet/ls.cljs, src/main/com/kubelt/ddt/cmds/wallet/rm.cljs, src/main/com/kubelt/ddt/options.cljs, src/main/com/kubelt/ipfs/client.cljc, src/main/com/kubelt/ipfs/spec.cljc, src/main/com/kubelt/lib/config.cljs, src/main/com/kubelt/lib/init.cljc, src/main/com/kubelt/lib/p2p.cljs, src/main/com/kubelt/lib/vault.cljc, src/main/com/kubelt/sdk.cljs, src/main/com/kubelt/sdk/v1.cljs, src/main/com/kubelt/spec/config.cljc, src/test/lib/config_test.cljs
Update the SDK `init` function to accept JWTs in the initialization options map. Provide a corresponding API call for retrieving the options map that will allow the SDK to be re-initialized with the same state.
Closes #312
Closes #329 
- separate r/w paths mean that we may need/want to make a call to each one during initialization
- these calls return node information that may be pertinent, e.g. Go vs JS flavor (which have different semantics for some commands)
- returned promise resolves after any such calls complete
- log level is now supplied as `:log/level` / `"log/level"`
- accept `credential/jwt` key in SDK options map
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
=> feat(sdk): accept JWTs in SDK init options map

.github/workflows/develop.yaml, bb.edn, dapp/.gitignore, dapp/test/dapp/integration/auth_test.cljs, package-lock.json, package.json, shadow-cljs.edn, src/test/car/block_test.cljs, src/test/car/build_test.cljc
- Updates some namespace refs which were failing test compilation
- Adds re-frame/test + shadow-cljs aliases for testing events and subscriptions
- Basic test for wallet init
- More tests to be written once wallet functions are ported to `:browser` target 
Updates 2/4 tasks in https://github.com/kubelt/kubelt/issues/317
#New tests passing on CI
=> chore(dapp): Re-frame tests w/karma for local + CI testing

www/content/en/blog/01-hello-world/index.md
=> Polish Pass

.github/workflows/release.yaml
Update the release workflow to include docker container for cloudflare-worker and cache Cypress dependency
=> chore(all-modules): Include cf-worker in release  + cache Cypress

.github/workflows/next.yaml
Also needs to update this build which calls the `test:all:release` and is actually triggered on merges.
=> chore(all-modules): Include cf-worker in build + cache Cypress

www/content/en/blog/01-hello-world/index.md
=> docs(blog): Spelling fixes only.

src/main/com/kubelt/lib/config/system.cljc, src/main/com/kubelt/lib/error.cljc, src/main/com/kubelt/sdk/v1.cljs, src/main/com/kubelt/spec.clj, src/main/com/kubelt/spec/config.cljc
the idea is use different validations inside any logic ... (without having several nested if/elses)
=> chore(spec-macro): Simplify calling spec conform logic

README.md, src/main/com/kubelt/sdk/v1/core.cljs
Fixes the broken build as well as updates the badge in the readme to reflect the correct status.
Closes https://github.com/kubelt/kubelt/issues/364
=> chore(dapp/integration-tests): Update how JWT is retrieved from response body to fix tests + correct build badge

packages/ddt/package-lock.json, packages/kbt/package-lock.json
Fix https://github.com/kubelt/kubelt/security/dependabot
=> Fix/dependatbot 73 & 72

package-lock.json, package.json
Remove unused? @webpack-cli/generators dep to fix https://github.com/kubelt/kubelt/security/dependabot/74
=> Fix dependabot

src/main/com/kubelt/lib/config/system.cljc, src/main/com/kubelt/lib/init.cljc
Data oriented (explicit and easy to visually follow) how options are extracted and merged into system-config
=> Refactor logic to merge optional options with system-default ones

dapp/src/dapp/components/dashboard/cta.cljs, dapp/src/dapp/core.cljs, dapp/src/dapp/wallet.cljs
Review on #375
- having an error following this flow: connecting and disconnecting then connecting again https://github.com/kubelt/kubelt/pull/378/commits/cc073cec53451cfc06e3a8317cb32ced564fde58
- don't expose or access to dapp db outside re-frame https://github.com/kubelt/kubelt/pull/378/commits/b46213f37d1758b1c539f62a0529435562515f3a
=> Review on #375

dapp/cypress/integration/routes.spec.js, dapp/src/dapp/components/dashboard/cta.cljs, dapp/src/dapp/components/sidebar.cljs, dapp/src/dapp/pages/apps.cljs, dapp/src/dapp/pages/dashboard.cljs, dapp/src/dapp/routes.cljs
- Met with Ondrej to address design feedback
- Rename `cores` to `apps` across UI/router/sidebar + update tests
=> chore(dapp): Address design comments + rename Cores -> Apps

src/main/com/kubelt/rpc/schema/fs.cljc
To test it
```clojure
(-> (read-schema "/Users/tangrammer/git/kubelt/kubelt/fix/openrpc/ethereum.json")
(lib.promise/then (fn [schema]
(println schema)))
(lib.promise/catch (fn [err] (println err))))
```
=> Add com.kubelt.rpc.schema.fs/read-schema node support

src/main/com/kubelt/ddt/cmds/rpc.cljs, src/main/com/kubelt/ddt/cmds/rpc/call.cljs, src/main/com/kubelt/ddt/cmds/rpc/core.cljs, src/main/com/kubelt/ddt/cmds/rpc/core/config.cljs, src/main/com/kubelt/ddt/cmds/rpc/core/config/get.cljs, src/main/com/kubelt/ddt/cmds/rpc/core/config/set.cljs, src/main/com/kubelt/rpc.cljc, src/main/com/kubelt/rpc/request.cljc, src/main/com/kubelt/sdk/v1/core.cljs, src/main/com/kubelt/spec/rpc/init.cljc
Add ddt support for get/set core config
- `ddt.js rpc core config get -w default`
```clojure
{:general {:client {:ttl 453},
:aliases [],
:metadata {:tags [],
:version 2022-05-25}},
:security {:auth {:jwt {},
:nonce {}},
:cors [],
:signers [],
:roles [],
:policies [],
:capabilities []}} 
```
- `ddt.js rpc core config get -w default :general:client`
```clojure
{:ttl 453}
```
- `ddt.js rpc core config set :general:client "{:ttl 999}" -f true -w default`
```clojure
CURRENT CONFIG->
{:general {:client {:ttl 453},
:aliases [],
:metadata {:tags [],
:version 2022-05-25}},
:security {:auth {:jwt {},
:nonce {}},
:cors [],
:signers [],
:roles [],
:policies [],
:capabilities []}}
TRYING NEW CONFIG ...
{:general {:client {:ttl 999},
:aliases [],
:metadata {:tags [],
:version 2022-05-25}},
:security …
```
=> Add ddt core config get/set support

deps.edn, project.clj, shadow-cljs.edn
Updates several dependencies:
- `camel-snake-kebab` to `0.4.3`
- `org.web3/crypto` to `5.0.0`
- `org.web3/utils` to `5.0.0`
- `org.clojure/clojurescript` to `1.11.54`
- `fipp` to `0.6.26`
- `com.github.mainej/headlessui-reagent` to `1.6.3.67`
- `day8.re-frame/re-frame-10x` to `1.3.0`
=> chore: update some dependencies

fix/openrpc/oort.json
Include OpenRPC schema for Oort as fixture data and as a development convenience.
=> chore(rpc): add oort OpenRPC schema fixture

www/config/_default/params.toml
Front page is looking for params that don't exist
Closes #427
=> bug(www) > add front page social urls and icons

shadow-cljs.edn
Add com.kubelt.spec.* ns tests to sdk-test build
=> Add com.kubelt.spec.* ns tests to sdk-test build

src/main/com/kubelt/ddt/auth.cljs, src/main/com/kubelt/spec/rpc/init.cljc
Fix for https://github.com/kubelt/kubelt/pull/415
=> Fix ddt rpc core config

dapp/src/dapp/wallet.cljs, src/main/com/kubelt/ddt/auth.cljs, src/main/com/kubelt/lib/config/system.cljc, src/main/com/kubelt/lib/p2p.cljs, src/main/com/kubelt/sdk/v1/core.cljs, src/test/com/kubelt/rpc/auth_test.cljs
- Add support for sdk-cljs integration tests using [https://oort-devnet.admin1337.workers.dev:443](https://oort-devnet.admin1337.workers.dev/)
- Also refactor [com.kubelt.sdk.v1.core/authenticate!](https://github.com/kubelt/kubelt/pull/437/commits/cf06783e761b26084c51bb2df199c6e59cf6e409)
=> SDK rpc core auth test

deps.edn, shadow-cljs.edn
=> chore: update deps, introduce tick

dapp/src/dapp/core.cljs, dapp/test/dapp/sdk_test.cljs, src/main/com/kubelt/lib/config/sdk.cljc, src/main/com/kubelt/lib/json.cljc, src/main/com/kubelt/lib/storage/browser.cljs, src/test/com/kubelt/rpc/test_commons.cljs
=> Add storage/browser impl

project.clj, shadow-cljs.edn, src/main/com/kubelt/lib/promise.cljc, src/main/com/kubelt/lib/promise.cljs, src/test/com/kubelt/rpc/auth_test.cljs, src/test/com/kubelt/rpc/profile_test.cljs
Wrapping funcool.promesa in kubelt.lib.promesa
=> chore(deps): Use funcool/promesa

dapp/test/dapp/sdk_test.cljs
=> Fix S-expression

src/main/com/kubelt/lib/http/browser.cljs
The browser does not permit some headers to be set when making requests from the browser context. Remove those headers (currently just `User-Agent`) before sending HTTP requests on that platform.
=> fix(sdk): remove forbidden HTTP headers in browser context

README.md, oort/README.md
Adding a folder for the future open source version of oort for self hosting.
=> chore(oort): oort folder and readme

src/main/com/kubelt/lib/p2p.cljs, src/main/com/kubelt/sdk/v1/core.cljs
Does a bit of comment and whitespace cleanup of auth code.
=> chore(sdk): tweak comments, formatting around core auth

src/test/com/kubelt/rpc/schema_test.cljs
Show failing test in test summary if it fails
=> Detect failing test

src/main/com/kubelt/sdk/v1/oort.cljs
https://github.com/kubelt/kubelt-oort/pull/104#pullrequestreview-1006814166
=> Adapt to BE changes

fix/openrpc/oort.json, src/test/com/kubelt/rpc/nfts_test.cljs, src/test/com/kubelt/rpc/profile_test.cljs
Align-with/depends-on https://github.com/kubelt/kubelt-oort/pull/109
=> Update set profile picture

src/main/com/kubelt/lib/rpc.cljs, src/main/com/kubelt/sdk.cljs, three-id/src/provider/kubelt.ts
so we can auth/JWT rpc calls
to be merged on [feat/claim/add-whitelist-check](https://github.com/kubelt/kubelt/tree/feat/claim/add-whitelist-check)
=> Using rpc-client

src/main/com/kubelt/lib/rpc.cljs, src/main/com/kubelt/sdk.cljs, src/main/com/kubelt/sdk/v1/oort.cljs, three-id/src/provider/kubelt.ts, three-id/src/screens/Auth.tsx
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Closes https://github.com/kubelt/three-id/issues/74
=> FEAT(claim): Add whitelist check

bb.edn
Relates and complete
https://github.com/kubelt/kubelt/pull/506/commits/d6a35d5b5d7755a91ce0846480250c671dec24d1
=> Fix npm run test:all:release

bb/com/kubelt/cloudflare/kv.clj, three-id/package-lock.json, three-id/package.json
Used `@cloudflare/wrangler` by accident, when it's the 2.x version from package `wrangler` that we want. Fixed!
=> fix(3iD): use the right wrangler dependency

three-id/.env.example, three-id/src/provider/kubelt.ts, three-id/src/screens/Auth.tsx
Redirect to other property is no longer needed. As such its environment variables and helper functions are no longer needed.
=> FEAT(claim): remove redirect

three-id/src/provider/kubelt.ts
Closes https://github.com/kubelt/three-id/issues/87
=> FEAT(claim): Stored SDK in localStorage on succes auth to KBT

three-id/src/screens/Auth.tsx
> Please update screen 2B message by adding "It could take a few seconds for the message to appear. If it does not appear try clicking on your wallet."
References https://github.com/kubelt/three-id/issues/92
=> BUG(3iD): Polish Tracker - Auth copy

.actrc, .github/workflows/develop.yaml, .github/workflows/next.yaml, .github/workflows/ref-docs.yaml, .github/workflows/release.yaml, .gitignore, bb/com/kubelt/util.clj, package-lock.json, three-id/bb.edn, three-id/package-lock.json, three-id/package.json
Updates the `next` pipeline to build and deploy to staging environment.
=> chore(3iD): update build pipeline

three-id/package-lock.json
Update `three-id/package-lock.json` to address complaints in build workflow.
=> chore(3iD): update package-lock.json

three-id/package-lock.json, three-id/package.json
Updates a number of minor/patch-level 3iD dependencies. The remaining updates have a larger footprint (e.g. because of major version update or associated peer dependencies) and should probably be handled _en masse_.
NB: these changes deployed to my development environment.
=> chore(3iD): update dependencies

.github/workflows/next.yaml, three-id/bb.edn
Set some additional environment variables in `next` workflow.
=> chore(3iD): update next workflow

.github/workflows/next.yaml, bb.edn, three-id/bb.edn
Some more pipeline tweaks to make local and remote execution less divergent.
=> fix(gha): tweak GHA next pipeline

.github/workflows/next.yaml, .github/workflows/release.yaml
The `release` workflow executes the same steps as for staging, with the exception that the deployment environment is different and the tag name is compiled in as the application version.
=> chore(gha): update release workflow

src/main/com/kubelt/lib/rpc.cljs, src/main/com/kubelt/sdk.cljs, src/main/com/kubelt/sdk/v1/oort.cljs, three-id/src/provider/kubelt.ts, three-id/src/screens/funnel/Gate.tsx
Adding sdk support to retrieve core claims
https://github.com/kubelt/kubelt/issues/563#issuecomment-1187609942
Relates #563 
So far, locally UI test with oort devnet, using a wallet with existent claims in devnet
-  [ ] TODO Unit test
=> Add sdk api support to get kbCoreGetClaims

three-id/src/analytics/datadog.ts, three-id/src/screens/funnel/Auth.tsx, three-id/src/screens/funnel/Gate.tsx, three-id/src/screens/funnel/Landing.tsx, three-id/src/screens/minting/Mint.tsx, three-id/src/screens/profile/Settings.tsx
RUM sessions get automatically recorded with the new URL format so manual registration of route events are no longer necessary.
Closes #567 
=> CHORE(Three-id): Remove manual analytics

bb/com/kubelt/github/secret.clj, three-id/bb.edn
Set a couple of additional secrets in the GitHub Workflow execution context.
=> chore(3iD): add some secrets to workflow environment

three-id/bb.edn
=> chore(alex): Add alex's dev env

.github/workflows/develop.yaml, src/main/com/kubelt/lib/util.cljc, src/test/com/kubelt/lib/test_utils.cljs, src/test/com/kubelt/rpc/oort_test.cljs, src/test/com/kubelt/rpc/test_commons.cljs, src/test/com/kubelt/sdk/v1/oort_test.cljs
Relates 
https://github.com/kubelt/kubelt/pull/566#issuecomment-1187778097
and 
https://github.com/kubelt/kubelt/pull/566#issuecomment-1189233497
=> chore(3iD): Use metamask test wallet from GHA secrets to to test sdk/claims

three-id/worker/wrangler.toml.example
Add missing wrangler configuration to the `wrangler.toml.example` template for Alex's development environment.
=> chore(3iD): add wrangler config to template for alex

bb/com/kubelt/git.clj, three-id/bb.edn
Add some helper tasks for tag-based releasing.
=> chore(3iD): add helper for tag-based release flow

.github/workflows/develop.yaml, three-id/tests/e2e/specs/gate-spec.js
=> feat(three-id): Create automation testing workflow for three-id gate

src/main/com/kubelt/lib/io/node.cljs, src/main/com/kubelt/lib/rpc.cljs, src/main/com/kubelt/lib/storage/node.cljs, src/main/com/kubelt/lib/wallet.cljc, src/main/com/kubelt/lib/wallet/node.cljs, src/main/com/kubelt/sdk/v1.cljs, src/main/com/kubelt/spec/config.cljc, src/main/com/kubelt/spec/jwt.cljc, src/main/com/kubelt/spec/vault.cljc, src/main/com/kubelt/spec/wallet.cljc, src/test/com/kubelt/rpc/nfts_test.cljs, src/test/com/kubelt/rpc/sdk_test.cljs
Relates https://github.com/kubelt/kubelt/pull/575
Mainly we try to fix bugs adding specs and test coverage
=> Bug(sdk): Fix restored system with rpc calls

src/main/com/kubelt/sdk/v1/oort.cljs
Relats https://github.com/kubelt/kubelt/pull/586
Revert changes lost due to the order that last Prs were merged
=> Fix lost changes

three-id/src/analytics/datadog.ts, three-id/src/hooks/account.ts, three-id/src/hooks/sdkAuth.ts, three-id/src/provider/kubelt.ts, three-id/src/provider/web3.ts, three-id/src/screens/funnel/Auth.tsx, three-id/src/screens/funnel/Gate.tsx, three-id/src/screens/funnel/Landing.tsx, three-id/src/screens/profile/Settings.tsx
Fixed settings uncontrolled components
Fixed controlled inputs
Made behavior more deterministic
Updated UX for the entire funnel, as well as the settings screen to increase overall quality:
- Better redirects
- Better handling of refresh
- Better handling of landing on specific pages
- Better handling of account state
- ...
Closes #599 
- [x ] I have performed a self-review of my code
=> CHORE(Three-id): Properly respond to try wallet

fix/openrpc/oort.edn, fix/openrpc/oort.json, src/main/com/kubelt/lib/oort.cljs, src/main/com/kubelt/sdk/v1/oort.cljs, src/test/com/kubelt/rpc/profile_test.cljs, src/test/com/kubelt/rpc/schema_test.cljs, three-id/src/provider/kubelt.ts
Align with https://github.com/kubelt/kubelt-oort/pull/139
```
#+BEGIN_SRC shell
curl http://localhost:8787/@0xB00b95Fc8ff4709F61496a9BBc2E5704207b5BB5/jsonrpc \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"rpc.discover","params":[],"id":1,"jsonrpc":"2.0"}' | jq '.result.methods[].name'
#+END_SRC
#+RESULTS:
| kb_ping            |
| kb_pong            |
| kb_auth            |
| kb_auth_verify     |
| kb_core_create     |
| kb_core_add_signer |
| kb_core_get_claims |
| kb_get_config      |
| kb_set_config      |
| kb_set_profile     |
| kb_get_profile     |
| kb_metrics_submit  |
| alchemy_getNFTs    |
```
```clojure
[[:alchemy :get-nf-ts]
[:kb :add-core-signer]
[:kb :create-core]
[:kb :get-config]
[:kb :get-core-claims]
[:kb :get-nonce]
[:kb :get-profile]
[:kb :ping] …
```
=> BUG(rpc): Align with kubelt-oort/pull/139

three-id/bb.edn
When purging the cache by URL, purge cache entries using both the internal as well as the external-facing host names.
=> chore: purge internal URLs

package-lock.json
Fix  build, relates to https://github.com/kubelt/kubelt/pull/613
=> BUG(build): Add package-lock.json with reference to new starbase file

shadow-cljs.edn
Relates https://github.com/kubelt/kubelt/pull/613
=> BUG(build): Fix build:starbase:release-cljs

3iD/bb.edn
Remove user-specific tasks for working with development environment.
=> chore(3iD): remove user-specific dev environment tasks

3iD/README.md
Updated readme to hopefully make it easier for new onboards to run the solution locally.
Closes #CHORE(3ID): Update readme docs
=> CHORE(3iD): Update readme docs

.github/workflows/next.yaml, README.md, www/content/en/docs/basics/introduction.md
=> fix(gha): fix guide link and gha

.github/workflows/release.yaml, 3iD/README.md, 3iD/bb.edn, 3iD/deploy.edn.example, 3iD/package.json, 3iD/worker/wrangler.toml.example, README.md, default.nix
=> fix(gha): scripts

.github/workflows/next.yaml, 3iD/package.json
Quick test fix for intermittent ui test fails
=> fix(gha): cache cypress

.github/workflows/next.yaml
New synpress testing requires a change of environment variables
=> FIX(3iD-test): Fix GHA

3iD/README.md, 3iD/src/App.tsx, 3iD/tests/e2e/.eslintrc.js, 3iD/tests/e2e/synpress.json, 3iD/tests/e2e/tsconfig.json, 3iD/tests/support/commands.js, 3iD/tests/support/index.js
Aligned testing folder to 3iD project formatting.
=> CHORE(3iD): Formatting

3iD/src/provider/kubelt.ts, 3iD/src/provider/web3.ts, 3iD/src/screens/minting/Mint.tsx
Confirmation screen & try again handler
Closes #662
=> CHORE(Mint): Confirm Transaction

.github/workflows/next.yaml, .github/workflows/release.yaml, 3iD/bb.edn, bb.edn
Add DD env to fix dashboards
Closes # (issue)
Not tested
=> (chore): dd env

3iD/bb.edn
Small typo fix, removes a dangling brace.
=> fix: remove a dangling brace

3iD/src/provider/kubelt.ts
There's a case in which undefined cannot be interpreted as JSON.
=> FIX(3iD): Undefined funnel state

.github/workflows/release.yaml, nftar/cloudbuild.yaml
Fix for whitespace and line length errors, etc.
=> fix(lint): Fix `yamllint` Errors

3iD/src/App.tsx, 3iD/src/screens/minting/Mint.tsx, 3iD/src/screens/onboarding/Onboard.tsx
General setup for onboarding screen; location in funnel.
Closes #686
=> CHORE(Onboarding): Create onboarding screen

3iD/src/screens/onboarding/Onboard.tsx
Added function-less mint banner
Closes #690
=> CHORE(onboarding): Mint banner

nftar/src/app.js
=> chore(nftar): cache gateway

3iD/src/provider/kubelt.ts
=> FEAT(3id): Replace kb_getProfile and kb_setProfile methods

3iD/.env.example, 3iD/src/provider/kubelt.ts, 3iD/src/screens/funnel/Auth.tsx, 3iD/src/screens/funnel/Invite.tsx, 3iD/src/screens/funnel/Landing.tsx, 3iD/src/screens/profile/Details.tsx, 3iD/src/screens/profile/Settings.tsx
Updated env variables for twitter and discord
Removed naming screen
Updated to unlock flow for 15th
=> FIX(3iD): Various fixes

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE.md, .github/settings.yml
Cleaning up templates.
Untested.
=> chore(github): Updates to issues, PR templates, and settings.

.github/settings.yml
Settings yaml was behind pulumi.
Live
=> fix(settings): Update settings.yaml to agree with Pulumi.

3iD/src/provider/kubelt.ts, 3iD/src/screens/minting/Mint.tsx
Initial assumption of getPFP req / res flow needs adjustment. This is the adjustment.
Manually
=> CHORE(3iD): Adapt mint call

3iD/src/provider/kubelt.ts, 3iD/src/screens/funnel/Invite.tsx, 3iD/src/screens/minting/Mint.tsx
Use public gateway to display image
Manually
=> FIX(3iD): Load IPFS from gateway

eth/invite/LICENSE.md, eth/invite/hardhat.config.ts, eth/invite/package-lock.json, eth/invite/package.json, eth/invite/scripts/deploy.ts
Updated license, enabled mainnet deployment, updated baseline metadata link.
Live prod deployment and testing on Friday.
=> feat(invite): Housekeeping updates to invitation smart contract repo.

eth/invite/README.md, eth/invite/hardhat.config.ts
Instructions for deployment. Also added a clarifying comment for the Alchemy config loader.
Local hardhat.
=> docs(README): Added brief intro and deployment workflow instructions.

3iD/src/screens/funnel/Invite.tsx, 3iD/src/screens/onboarding/Onboard.tsx
Updated 3iD onboarding copy
Closes #707 
Asymptotically
=> FIX(3iD): Update FAQ copy

eth/invite/README.md
Added a section about typechain regeneration when you switch branches.
NA docs
=> docs(README): Added Typechain Regeneration Information

3iD/README.md
Add instructions for cache busting.
=> docs(README): Add cache busting instructions.

.github/workflows/next.yaml, .github/workflows/release.yaml
Fixes assets loading from cache and breaking
Not tested
=> chore(cf): purge three id zone after deploy

.github/workflows/next.yaml, .github/workflows/release.yaml
=> chore(cf): purge update

.github/workflows/next.yaml, .github/workflows/release.yaml
=> fix(cf): purge

eth/invite/contracts/Invite.sol, eth/invite/hardhat.config.ts, eth/invite/package-lock.json, eth/invite/scripts/deploy.ts
Add a voucher system to mint an invite so, at a later time we can enable lazy minting.
Using hardhat
=> feat(voucher): invite vouhcer

eth/invite/contracts/Invite.sol, eth/invite/hardhat.config.ts, eth/invite/scripts/deploy.ts
Added Rinkeby as a target. Also added a `contract:destroy` command for Hardhat.
Local and testnet
=> feat(invite): Add Rinkeby, Destructor

eth/invite/contracts/Invite.sol, eth/invite/hardhat.config.ts, eth/invite/scripts/deploy.ts, package-lock.json
Construct operator wallet instance to perform signing of voucher.
=> chore(invite): tweak voucher signing

eth/invite/hardhat.config.ts
Add Polygon support to invite.
Local and Mumbai
=> feat(invite): Add Polygon.

3iD/src/components/side-menu/SideMenu.tsx
Adds hamburger menu for side menu for mobiles with default expanded false. 
=> chore(3id): hamburger menu for mobile

.github/workflows/release.yaml
Will return when properly configured
=> chore(gha): remove gpg check

3iD/package-lock.json, 3iD/package.json, 3iD/src/provider/web3.ts
Use Metamask's provider detector in the hopes of getting it to run in Metamask Mobile Browser.
Need it deployed to preview to test.
=> FEAT(3iD): Use Metamask's detect Ethereum provider

deps.edn, src/main/com/kubelt/lib/jwt.cljc, src/main/com/kubelt/sdk/v1/oort.cljs
Examine token expiry during logged-in status check.
=> fix(sdk): examine token expiry during login status check

threeid/app/routes/dashboard.tsx, threeid/app/routes/dashboard/index.tsx, threeid/app/routes/index.tsx
Fetches invite code with oortSend
=> chore(threeid): get invite code and votes

threeid/app/components/invite-code/index.tsx
Tooltip for inviteCode component
=> chore(3id): tooltip for invites

threeid/app/components/FAQ/AccordionComponent.tsx, threeid/app/components/FAQ/FAQ.scss, threeid/app/components/FAQ/index.tsx, threeid/app/components/invite-code/index.tsx, threeid/app/components/invite-code/inviteCode.scss
Add styles to FAQ and InviteCode components
=> chore(threeid): add styles to faq and invite

threeid/app/routes/auth/sign/$address.tsx
Metamask error object is different in ways that break error messages. Use a fixed error message when error is present.
=> fix(threeid): user error on sign

eth/test/PFP.ts
Noticed tests were failing -- fixed, mostly with deletia.
tldr is that there is no maximum number of profiles intended, so removed usage and validation of same from the test suite.
Local
=> fix(pfp): Updated unit tests to new contract interface.

threeid/app/routes/account/index.tsx, threeid/app/routes/auth/sign/$address.tsx
Fix empty json on boostrap votes
=> fix(Threeid): set bootstrap for votes

threeid/app/routes/account/index.tsx
=> fix(threeid): votes 2

threeid/app/routes/account/index.tsx, threeid/app/styles/base.scss
Fixes tooltip font and removes "Completed" from vote
=> fix(threeid): tooltip font

eth/bin/local_profile_smoke.sh, eth/profile.config.ts, nftar/src/app.js
Added the signature to the voucher directly so the called doesn't have to do so. Changed hardhat commands to reflect that change.
local and goerli
=> feat(nftar): Update NFTar Metadata

package-lock.json, package.json
`npm ci` in monorepo root is failing. This fixes.
=> fix(build): Dependency Fix

threeid/app/routes/account.tsx, threeid/app/routes/account/index.tsx, threeid/app/routes/auth.tsx, threeid/app/routes/auth/gate/$address.tsx, threeid/app/routes/auth/nonce/$address.tsx, threeid/app/routes/auth/sign/$address.tsx, threeid/app/utils/constants.tsx, threeid/app/utils/rpc.server.tsx, threeid/app/utils/session.server.tsx, threeid/tests/helpers.ts
- Update oort requests to remove address and rely on jwt.  
- Add JWT helper
- Increase session time to 4 hours
- send template to oort for get nonce
=> fix(threeid): new message template for nonce and renew session

eth/contracts/PFP.sol, eth/test/PFP.ts
Disable transfers and add test for same.
Local and rink.
=> feat(pfp): Disable transfers and add test for same.

eth/test/PFP.ts
Remove console log from tests.
=> fix(pfp): Remove debug output from tests.

eth/contracts/PFP.sol
Fix solidity build warnings.
local
=> fix(pfp): Fix build warnings.

threeid/.env.example, threeid/app/routes/auth.tsx, threeid/app/routes/auth/gate/$address.tsx, threeid/app/utils/datadog.server.tsx, threeid/app/utils/rpc.server.tsx, threeid/app/utils/session.server.tsx, threeid/package-lock.json, threeid/package.json
Fixes redirect loop with new cookie times and introduces part implementation of datadog
Locally
=> chore(threeid): fix session on exp and dd events

threeid/app/routes/account.tsx, threeid/app/routes/auth.tsx, threeid/app/routes/auth/gate/$address.tsx, threeid/app/routes/auth/sign/$address.tsx, threeid/app/routes/onboard.tsx, threeid/app/routes/onboard/nickname/index.tsx
=> FIX(3iD): Move onboard check to account

threeid/app/routes/account.tsx, threeid/package.json
=> FEAT(3iD): Move onboard state from Oort to BFF

threeid/app/routes/auth/gate/$address.tsx, threeid/app/routes/onboard.tsx, threeid/app/routes/onboard/mint/index.tsx, threeid/app/routes/onboard/mint/load-voucher.tsx, threeid/app/routes/onboard/nickname/index.tsx
Added a NFTar 409 handler.
Visually. With Alex.
=> FEAT(3iD): Adapt mint cache

threeid/app/components/head-nav/index.tsx, threeid/app/routes/account.tsx, threeid/app/routes/onboard/mint/load-voucher.tsx, threeid/wrangler.toml
=> chore(threeid): logs

threeid/app/components/head-nav/index.tsx, threeid/app/routes/account.tsx
=> fix(threeid): hex style

threeid/app/components/buttons/Button.scss, threeid/app/components/buttons/Button.tsx, threeid/app/components/buttons/index.ts
Adapted button components to match design system. In this particular case:
- Added focus state
- Added disabled property & state
Visually
=> FEAT(3iD-UI): Button focus & disabled

threeid/app/routes/onboard/mint/load-voucher.tsx
Fixes image set when image is first generated.
=> fix(threeid): image

threeid/app/components/inputs/InputText.tsx, threeid/app/components/typography/Text.tsx, threeid/app/routes/kitchensink.tsx
Added a kitchensink with all current components plastered on. 
- Typography
- Buttons
- Text input
No need for testing. Visually if anything.
Problem with applying Tailwind error styles to input components.
=> SPIKE(3iD-UI): Kitchensink

redeem/app/routes/$invite.tsx, redeem/app/routes/proof.tsx, redeem/app/routes/redeem.tsx, redeem/package-lock.json
=> fix(redeem) proof

redeem/app/root.tsx, redeem/app/routes/$invite.tsx, redeem/app/routes/redeem.tsx, redeem/wrangler.toml, threeid/app/root.tsx
Fast fix for invite code lookup
=> fix(redeem): invite code lookup

redeem/app/routes/$invite.tsx, redeem/app/routes/success.tsx
=> fix(redeem): invite type

redeem/app/routes/$invite.tsx, redeem/app/routes/index.tsx, redeem/app/routes/redeem.tsx
=> fix(redeem): invite redirect

redeem/app/root.tsx, redeem/app/routes/proof.tsx, redeem/app/routes/redeem.tsx
Quick fix for redeem styles and error
=> fix(redeem): styles and error

threeid/app/components/head-nav/index.tsx
Added a headnav state for when a user is not authenticated.
Visually manual
=> FEAT(3iD): Unauth headnav

.github/workflows/main.yaml, .github/workflows/next.yaml, .github/workflows/release.yaml, nftar/README.md, nftar/src/app.js, nftar/src/views/nftar.js, redeem/app/routes/index.tsx, redeem/app/routes/proof.tsx, redeem/app/routes/success.tsx, threeid/.env.example, threeid/app/root.tsx, threeid/app/routes/auth/index.tsx, threeid/tests/fixtures/voucher.json, threeid/wrangler.toml, www/content/en/docs/guides/3ID/quickstart/index.md
Migrate 3id dapp url to kubelt domain to elinate brand confusion.
wrangler
=> chore(domains): migrate dapp.threeid.xyz to 3id.kubelt.com

threeid/app/components/profile/ProfileCard.tsx, threeid/app/routes/$profile.json.tsx, threeid/app/routes/$profile.tsx
Until we enable this as part of the profile schema, it should be hidden. Also removed some leftover console logging.
Visually
=> FIX(3iD-Profile): Hide date on profile & rem logs

smartcontracts/eth/pfp-invites/hardhat.config.ts
Fixed a small bug where hardhat config was still trying to include the crdt config, which we've factored into another project.
Local and goerli.
=> fix(eth): Fixed a small bug in the ethereum hardhat config

.github/workflows/main.yaml, .github/workflows/next.yaml, .github/workflows/release.yaml
Fixes failed deploy to dev envs
=> fix(gha): wrkdir for deploy

.github/workflows/main-crdt.yaml, .github/workflows/main-galaxy.yaml, .github/workflows/main-nftar.yaml, .github/workflows/main-oort.yaml, .github/workflows/main-redeem.yaml, .github/workflows/main-threeid.yaml, projects/galaxy/package.json, projects/galaxy/wrangler.toml, projects/threeid/package.json
=> fix(gha): main deploy failures

projects/threeid/.dev.vars.example, projects/threeid/app/components/head-nav/index.tsx, projects/threeid/app/helpers/voucher.ts, projects/threeid/app/routes/$profile.json.tsx, projects/threeid/app/routes/$profile.tsx, projects/threeid/app/routes/account.tsx, projects/threeid/app/routes/account/dashboard.tsx, projects/threeid/app/routes/account/settings/profile.tsx, projects/threeid/app/routes/onboard.tsx, projects/threeid/app/routes/onboard/mint/index.tsx, projects/threeid/app/routes/onboard/mint/load-voucher.tsx, projects/threeid/app/routes/onboard/name.tsx
=> FEAT(3ID): Align to Galaxy

projects/galaxy/src/schema/gql/profile.ts, projects/galaxy/src/schema/resolvers/profile.ts, projects/threeid/app/routes/account.tsx, projects/threeid/app/routes/account/dashboard.tsx, projects/threeid/app/routes/account/settings/profile.tsx
Updates the roadmap on dashboard and some other small fixes 
=> fix(3id): dashboard upgrade

.github/workflows/main-galaxy.yaml, .github/workflows/main-threeid.yaml, .github/workflows/next-galaxy.yaml, .github/workflows/next-redeem.yaml, .github/workflows/next-threeid.yaml, .github/workflows/release-galaxy.yaml, .github/workflows/release-threeid.yaml, projects/galaxy/wrangler.toml, projects/threeid/wrangler.toml
Fixes breaking builds on main
gha
=> fix(gha): deploys

projects/threeid/app/components/profile/ProfileCard.tsx, projects/threeid/app/routes/$profile.tsx, projects/threeid/app/routes/account/settings/profile.tsx
Some small fixes / hacks.
Demoally
=> FIX(3iD): Pre deployment hacks

.github/workflows/main-console.yaml, .github/workflows/main-galaxy.yaml, .github/workflows/main-nftar.yaml, .github/workflows/main-oort.yaml, .github/workflows/main-redeem.yaml, .github/workflows/main-threeid.yaml, .github/workflows/next-console.yaml, .github/workflows/next-galaxy.yaml, .github/workflows/next-oort.yaml, .github/workflows/next-redeem.yaml, .github/workflows/next-threeid.yaml, .github/workflows/release-oort.yaml, .nvmrc, apps/package.json, packages/package.json, yarn.lock
Fixes deploy to main branch
gha
=> fix(gha): main deploy issues

.github/workflows/next-console.yaml, .github/workflows/next-galaxy.yaml, .github/workflows/next-redeem.yaml, .github/workflows/next-threeid.yaml, .github/workflows/release-console.yaml, .github/workflows/release-galaxy.yaml, .github/workflows/release-redeem.yaml, .github/workflows/release-threeid.yaml, README.md
Fixes next and release deploy deficiencies
gha
=> fix(gha): next depoy issues

.github/workflows/main-icons.yaml, .github/workflows/next-icons.yaml, .github/workflows/release-icons.yaml, .gitignore, README.md, platform/icons/.dev.vars.example, platform/icons/src/index.ts, platform/icons/wrangler.toml
Set up GitHub Actions workflows for `icons` service.
=> chore(icons): set up GHA workflows

apps/console/package.json, apps/passport/package.json, apps/threeid/package.json, package.json, platform/galaxy/package.json, platform/icons/package.json, platform/oort/package.json, platform/starbase/worker/package.json, projects/redeem/package.json, yarn.lock
Bump `wrangler` to `2.1.15` everywhere it's being used.
=> chore: update wrangler

apps/threeid/app/components/buttons/Button.tsx, apps/threeid/app/components/buttons/ButtonLink.tsx, apps/threeid/app/components/inputs/InputTextarea.tsx, apps/threeid/app/routes/$profile.tsx, apps/threeid/app/routes/account/settings/profile.tsx, apps/threeid/app/routes/api/upload-cover.tsx, apps/threeid/app/routes/api/upload-image.tsx, apps/threeid/tailwind.config.js, apps/threeid/wrangler.toml
- Added capability to upload pfp
- Added capability to upload cover photo
- Added service link to ICON platform project
Manually; there are some areas that require a bit more attention, but I believe that should be on another branch.
=> FEAT(3iD): Upload PFP

apps/threeid/app/helpers/validate-proof.ts, apps/threeid/app/routes/$profile.tsx, apps/threeid/package.json, platform/icons/package.json, platform/icons/wrangler.toml, yarn.lock
Hook up OG:Image renderer.
Local / testnet
- [na] New and existing unit tests pass locally with my changes
=> feat(threeid): Add OG Image

.github/workflows/main-threeid.yaml, .github/workflows/next-threeid.yaml, .github/workflows/release-threeid.yaml, apps/threeid/app/routes/nfts/index.tsx
Needed for querying NFTs; will fail unless it exists. Don't forget to set it in the GHA!
This is the test
=> FIX(3iD-Deploy): Alchemy env vars

projects/nftar/src/app.js, projects/nftar/src/traits.js, projects/nftar/tests/utils.test.js
Remove 409 check, continue refactoring and error checking.
Local
=> feat(nftar): Remove 409 Check, Bugfixes and Error Checking

apps/threeid/app/routes/$profile.tsx
Moar social tags.
Local
- [na] New and existing unit tests pass locally with my changes
=> feat(threeid): Add More OG:Tags

apps/threeid/app/routes/$profile.tsx
Just added a small space for the profile; visible on medium and small devices.
Visually
=> FEAT(3iD): Profile spacing

apps/threeid/app/helpers/voucher.ts, apps/threeid/app/routes/$profile.json.tsx, apps/threeid/app/routes/$profile.tsx, apps/threeid/app/routes/nfts/index.tsx, apps/threeid/app/routes/onboard/mint/load-voucher.tsx, apps/threeid/app/routes/onboard/name.tsx, apps/threeid/app/utils/alchemy.server.tsx, packages/components/pnpm-lock.yaml, platform/galaxy/src/schema/types/profile.ts
Do the voucher check for pfp in the bff to make state management easier. Heal the voucher cache if found.
=> chore(threeid): check for minted pfp in bff

apps/threeid/app/routes/$profile.tsx
Improved Twitter social shares.
na
=> feat(threeid): Twitter Meta Tags

.github/workflows/pr-apps.yaml, .github/workflows/pr-packages.yaml, .github/workflows/pr-platform.yaml, .github/workflows/pr-projects.yaml
=> fix(gha): pr cache

platform/starbase/component/application/package.json, platform/starbase/component/contract/package.json, platform/starbase/component/user/package.json, yarn.lock
Remove the `file://` dependency refs that escaped last time.
=> fix: update more cross-workspace deps

apps/threeid/tailwind.config.js
- Closes #971 
Reproduced locally; fixed locally.
=> bug(threeid): tailwind paths

apps/threeid/app/routes/$profile.tsx
Added linebreak for potential long bios
- Closes #974 
Visually
=> fix(threeid): bio linebreak

apps/threeid/app/routes/account/settings/profile.tsx
Added a client side & server side check for valid URLs in profile details settings screen form
- Closes #972 
Local flow
=> feat(threeid): profile website regex

apps/threeid/app/routes/nfts/index.tsx
Added naive parsing for NFTs with OpenSea contract metadata associated so we get more NFT loads; also re-added a regression where pagination was not working anymore.
Ran the profile locally
=> fix(3id): nft page size and opensea schema

apps/threeid/app/utils/alchemy.server.tsx
Added spam filtering for NFT collection
Loaded the gallery locally
=> feat(3id): nft collection filtering

apps/threeid/app/components/nft-collection/NftModal.tsx, apps/threeid/app/routes/nfts/index.tsx, apps/threeid/app/utils/alchemy.server.tsx
Removed an assumption that NFT metadata properties will all have title also appended a different kind of object for OpenSea NFTs based on out in the wild responses.
Ran problematic profiles locally
=> Removed NFT property title assumption & added openSea object

apps/threeid/app/components/nft-collection/ModaledNft.tsx, apps/threeid/app/routes/nfts/index.tsx, apps/threeid/app/utils/alchemy.server.tsx
=> feat(3id): hide error'd nfts and use thumbnails

platform/worker-commons/.eslintrc.json, platform/worker-commons/.prettierrc, platform/worker-commons/package.json, platform/worker-commons/src/constants.ts, platform/worker-commons/src/durable_object.ts, platform/worker-commons/src/index.ts, platform/worker-commons/src/jsonrpc.ts, platform/worker-commons/src/routers/core.ts, platform/worker-commons/src/routers/cors.ts, platform/worker-commons/src/routers/errors.ts, platform/worker-commons/src/routers/index.ts, platform/worker-commons/src/routers/openrpc.ts, platform/worker-commons/src/utils/getCoreId.ts, platform/worker-commons/src/utils/index.ts, platform/worker-commons/tsconfig.json, platform/yarn.lock
A set of common modules providing the basics of a platform worker.
- Manual
=> feat(workers): introduce `@kubelt/worker-commons` package

apps/threeid/app/routes/$profile.tsx
Update og:tags to improve Discord support.
ngrok
=> feat(threeid): Update og:tags

apps/threeid/app/components/head-nav/index.tsx, apps/threeid/app/components/inputs/InputText.tsx, apps/threeid/app/components/nft-collection/ModaledNft.tsx, apps/threeid/app/components/sign-out-link/index.tsx, apps/threeid/app/routes/account.tsx, apps/threeid/app/routes/account/settings.tsx, apps/threeid/app/routes/account/settings/profile.tsx, apps/threeid/app/styles/auth.scss, apps/yarn.lock
Addressed most Figma feedback. Keeping the profile ones for another PR where I rework the profile.
Visually
=> fix(threeid): ux wins

apps/threeid/app/components/head-nav/index.tsx, apps/threeid/app/root.tsx, apps/threeid/app/routes/$profile.json.tsx, apps/threeid/app/routes/$profile.tsx, apps/threeid/app/routes/auth/index.tsx, apps/threeid/app/styles/auth.scss
- pepe error screens
- ens lookup fix
- ens data merge
=> fix(threeid): profile fixes

apps/threeid/app/components/buttons/Button.scss, apps/threeid/app/components/buttons/index.ts, apps/threeid/app/components/spinner/index.tsx, apps/threeid/app/helpers/gateway-from-ipfs.ts, apps/threeid/app/routes/$profile.tsx, apps/threeid/app/styles/base.scss, apps/threeid/tailwind.config.js
Addressed additional UI and UX concerns, such as:
- Additional button types
- Spinner variation
- Public profile layout 
- Cover photos
- Public avatars
- NFT schema
- Reflow mobile layout
Visually on public claimed and unclaimed profiles
=> feat(threeid): rework profile

platform/passport-worker/.eslintrc.json, platform/passport-worker/.gitignore, platform/passport-worker/.prettierrc.json, platform/passport-worker/package.json, platform/passport-worker/src/constants.ts, platform/passport-worker/src/core.ts, platform/passport-worker/src/index.ts, platform/passport-worker/src/openrpc.json, platform/passport-worker/src/types.ts, platform/passport-worker/tsconfig.json, platform/passport-worker/wrangler.toml, platform/ping-worker/.eslintrc.json, platform/ping-worker/.gitignore, platform/ping-worker/.prettierrc.json, platform/ping-worker/package.json, platform/ping-worker/src/core.ts, platform/ping-worker/src/index.ts, platform/ping-worker/src/openrpc.json, platform/ping-worker/src/types.ts, platform/ping-worker/tsconfig.json, platform/ping-worker/wrangler.toml, yarn.lock
Initial passport core worker.
- Manual
=> feat(passport): introduce `@kubelt/passport-worker` package

projects/nftar/src/traits.js, projects/nftar/tests/utils.test.js
Courtyard recently migrated from Polygon to Ethereum, and thisis the new address.
Minimal change of an address to correct it.
=> Update Courtyard contract address

projects/nftar/Dockerfile, projects/nftar/package.json, projects/nftar/src/app.js, projects/nftar/tests/datauri.js
Add new correct image generator based on chromium.
Local
=> feat(nftar): Add tests and new image generator.

packages/openrpc/component/index.ts, platform/starbase/.gitignore, platform/starbase/curl/kb_initPlatform.json, platform/starbase/package.json, platform/starbase/src/index.ts, platform/starbase/wrangler.toml
Provides a mechanism by which app core fixture data can be loaded as app cores as needed.
=> feat(sb): init app cores from fixture data

apps/threeid/app/components/nft-collection/ModaledNft.tsx
Added cursor to modaled nft (i.e. public profile listing renderer)
Visually
=> fix(threeid): modaled nft cursor

apps/console/package.json, apps/yarn.lock
Fix a build issue by toggling the console `sideEffects` setting, and update the app dependencies.
=> chore(console): update deps, fix a build error

apps/threeid/app/routes/$profile.json.tsx
=> Add CORS headers.

apps/threeid/app/components/head-nav/index.tsx, apps/threeid/app/routes/$profile.tsx, apps/threeid/app/routes/account.tsx, apps/threeid/app/routes/account/settings/profile.tsx
- Layout feedback
- Text sizing feedback
- Header feedback
- Closes #1036 
Visually & Chrome inspector
=> fix(threeid): varifixes

platform/starbase/data/state/kv/FIXTURES/local-console, platform/starbase/data/state/kv/FIXTURES/local-threeid
Add fixture data records for local starbase KV `FIXTURES`.
=> chore(sb): add some fixture data

packages/openrpc/impl/client.ts
The OpenRPC client returned by `discover()` was sending a fixed JSON-RPC request ID. Send an incrementing number as the request ID, and warning if the response ID doesn't match.
=> feat(openrpc): make client requests include incrementing IDs

platform/galaxy/src/env.ts, platform/galaxy/src/index.ts, platform/galaxy/src/schema/resolvers/profile.ts, platform/galaxy/src/schema/resolvers/utils/index.ts, platform/galaxy/wrangler.toml, platform/oort/src/packages/objects/objects.ts, platform/oort/src/routes/core/context.ts, platform/ping/wrangler.toml
If there's an Oort profile, migrate it to Account.
Local
=> feat(galaxy): Add Profile Migration Logic

packages/openrpc/build.js, packages/openrpc/component/index.ts, packages/openrpc/constants.ts, packages/openrpc/impl/client.ts, packages/openrpc/impl/context.ts, packages/openrpc/impl/index.ts, packages/openrpc/impl/jsonrpc.ts, packages/openrpc/impl/router.ts, packages/openrpc/impl/schema.ts, packages/openrpc/impl/scopes.ts, packages/openrpc/impl/utility.ts, packages/openrpc/package.json, packages/openrpc/tsconfig.json, platform/starbase/curl/kb_appDelete.json, yarn.lock
Various bits of cleanup suggested by the linter for the `@kubelt/openrpc` package. More to come in small increments until linter output is zilch.
=> fix(openrpc): various lint fixes and type tweaks

apps/threeid/app/routes/api/image-upload-url.tsx, apps/threeid/gql/profile.graphql, platform/galaxy/src/env.ts, platform/galaxy/src/index.ts, platform/galaxy/src/schema/index.ts, platform/galaxy/src/schema/resolvers/clients/cf-image-upload.ts, platform/galaxy/src/schema/resolvers/image.ts, platform/galaxy/src/schema/resolvers/index.ts, platform/galaxy/src/schema/types/images.ts, platform/galaxy/src/schema/types/index.ts, platform/galaxy/wrangler.toml
- Added an image upload client and its corresponding interface
- Exposed client img upload url gen functionality in galaxy
- Replaced threeid BFF with galaxy functionality
- Yoga GraphQL Playground
- Console logging
- Running avatar & cover upload flows
=> feat(galaxy): cloudflare image upload client

apps/passport/app/components/authentication/Authentication.tsx, apps/passport/app/components/authorization/Authorization.stories.mdx, apps/passport/app/components/authorization/Authorization.tsx, apps/passport/app/components/connect-button/ConnectButton.scss, apps/passport/app/components/connect-button/ConnectButton.tsx, apps/passport/app/platform.server.tsx, apps/passport/app/root.tsx, apps/passport/app/routes/authenticate/$address.sign.tsx, apps/passport/app/routes/authenticate/$address.token.tsx, apps/passport/app/routes/authorize/index.tsx, packages/design-system/index.ts, packages/design-system/src/atoms/button/Button.tsx, packages/design-system/src/atoms/spinner/Spinner.tsx, packages/design-system/src/build.ts, platform/access/src/authorization.ts, platform/access/src/jsonrpc.ts, platform/account/src/types.ts, platform/address/src/types.ts, platform/address/src/utils.ts, platform/galaxy/src/schema/resolvers/profile.ts
Hookup authorization flow to passport ui
Wrangler
=> feat(passport): authorize hookup

platform/address/src/jsonrpc.ts
Added env var check so terminal is clear when env vars are missing
- Closes #1116 
```
POST /jsonrpc 500 Internal Server Error (318.45ms)
[mf:err] POST /jsonrpc: Error: Missing env variable: NFTAR_CHAIN_ID
```
=> bug(system): address env check

apps/threeid/app/components/FAQ/index.tsx, apps/threeid/app/components/inputs/InputText.tsx, apps/threeid/app/components/inputs/InputTextarea.tsx, apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx, apps/threeid/app/components/typography/Heading.tsx, apps/threeid/app/components/typography/SmallRegularBlock.tsx, apps/threeid/app/routes/$profile.tsx, apps/threeid/app/routes/account/dashboard.tsx, apps/threeid/app/routes/account/settings/profile.tsx, packages/design-system/src/atoms/buttons/ButtonAnchor.tsx, packages/design-system/src/atoms/text/Text.tsx
Handled some visual regressions to better match initial design documents.
Most notably:
- Text
- Anchor buttons
Purely visual & workflow related
=> bug(threeid): css regressions

packages/design-system/index.ts, platform/galaxy/src/schema/resolvers/profile.ts, platform/galaxy/src/schema/resolvers/utils/index.ts
Makes oort historical only
On my local setup
=> galaxy: try/catch oort blocks

apps/passport/app/routes/authenticate/$address.token.tsx, apps/passport/package.json, apps/threeid/app/routes/$profile.tsx, platform/commons/src/urns.ts
Fixes to get profile ownership and linking working
Visual pairing
=> bug(threeid): profile ownership

apps/passport/tailwind.config.js
Added path to design system for tailwind configuration to properly generate element classes with custom attributes.
=>
Visually
=> fix(passport): ui regressions

apps/threeid/gql/nfts.graphql, packages/alchemy-client/index.ts, platform/galaxy/src/schema/resolvers/nfts.ts, platform/galaxy/src/schema/types/nfts.ts
Added pagination and multi network support for getNfts method
Flow
=> feat(alchemy): handle pagination

.github/workflows/main-access.yaml, .github/workflows/main-account.yaml, .github/workflows/main-address.yaml, .github/workflows/next-access.yaml, .github/workflows/next-account.yaml, .github/workflows/next-address.yaml, .github/workflows/release-access.yaml, .github/workflows/release-account.yaml, .github/workflows/release-address.yaml
=> chore(platform): add deployment workflows

apps/passport/.storybook/preview.js
Fixed storybook import path
No testing
=> fix(storybook): global import

apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx
Added a refresh token to the ProfileNFTCollection so that it may reload state when targeted account changes.
By toggling between two accounts
=> bug(threeid): gallery cache

apps/threeid/app/routes/$profile.json.tsx, apps/threeid/app/routes/$profile.tsx, apps/threeid/gql/ens.graphql, platform/galaxy/src/schema/resolvers/address.ts, platform/galaxy/src/schema/resolvers/clients/ens-utils.ts, platform/galaxy/src/schema/types/address.ts
Added ENS -> address resolution for the public profile parameter
- Closes #1174 
Flowing
=> bug(threeid): profile ens auth match

apps/threeid/app/components/accounts/settings/PfpNftModal.tsx, apps/threeid/app/components/nft-collection/NftModal.scss, apps/threeid/app/components/nft-collection/NftModal.tsx, apps/threeid/app/routes/$profile.tsx, apps/threeid/app/routes/nfts/index.tsx, apps/threeid/gql/nfts.graphql, packages/design-system/src/molecules/modal/Modal.tsx
Nft' modal includes details and collapse details and properties
- Closes #1165 
locally
=> Feat(threeid): upgrading nft modal

apps/passport/app/routes/apps.tsx, apps/threeid/app/components/head-nav/index.tsx, apps/threeid/app/routes/account/settings/profile.tsx, apps/threeid/wrangler.toml
Improves ui for settings button
- Closes #1171 
locally
=> chore(threeid): improves ui for settings button

.github/workflows/main-starbase.yaml, .github/workflows/next-starbase.yaml, .github/workflows/release-starbase.yaml
Contributes to closure of #1121 
- Chore
Has not been. The pipeline execution is the test.
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] My changes generate no new warnings
=> chore(gha): Env var cleanup and secrets naming refactor for Starbase.

apps/passport/app/routes/apps.tsx, apps/threeid/app/components/nft-collection/ModaledNft.tsx, apps/threeid/app/components/nft-collection/ProfileNftOneCollection.tsx, apps/threeid/app/routes/$profile/collection/$collection.tsx, apps/threeid/app/routes/$profile/index.tsx, apps/threeid/app/routes/nfts/collection.tsx, apps/threeid/app/routes/nfts/index.tsx, apps/threeid/gql/nfts.graphql, platform/galaxy/src/schema/resolvers/nfts.ts
Front-end for nft collections to display one nft per collection.
- Closes #1162 
Locally
=> feat(threeid): nft per collection

apps/passport/app/routes/apps.tsx
improve ui for buttons in the apps
locally
=> chore(passport): improves ui for buttons

apps/passport/app/root.tsx
Centered error div on full height container
- Closes #1193 
Visually
=> bug(passport): error screen positioning

CONTRIBUTING.md
=> chore(gha): Env var & secret docs

apps/threeid/app/routes/account/settings/profile.tsx
activates buttons whenever pfp changes
locally
=> fix(threeid): activate buttons on pfp change

projects/nftar/src/app.js, projects/nftar/src/utils.js
Error handler was missing `ctx` so pass it through. More generally we need a better answer for what happens if these images can't be retrieved, timeout, etc.
Local, goerli
- [na] New and existing unit tests pass locally with my changes
=> fix(nftar): Fix crash in error handler.

apps/threeid/app/components/nft-collection/ModaledNft.tsx, apps/threeid/app/components/nft-collection/NftModal.tsx, apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx, packages/design-system/src/molecules/modal/Modal.tsx, packages/design-system/src/pages/error/ErrorPage.tsx, platform/account/src/jsonrpc/index.ts
Improves UI for threeid profile.
- Closes #1234 
locally
=> Fix/threeid UI

.github/workflows/main-passport.yaml
Fixed value of secret used in Passport GHA dev workflow to match other apps
Not tested. Pipeline exec will allow testing.
=> fix(gha): Fixed value of secret used in Passport GHA dev workflow to match other apps

apps/threeid/app/components/accounts/settings/PfpNftModal.tsx, apps/threeid/app/components/nft-collection/ModaledNft.tsx, apps/threeid/app/components/nft-collection/NftModal.tsx, apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx, apps/threeid/app/routes/$profile/index.tsx
Fixes various UI bags related to css
=> fix(threeid): various css fixes

apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx
Design fix to not display filters when there is no nft
=> fix(threeid): filter hide on no nft

apps/threeid/app/assets/no-filter.svg, apps/threeid/app/components/nft-collection/ModaledNft.tsx, apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx
UI improvements for filters on profile page and for displaying less than 5 NFTs
In my local env
=> fix(threeid): css on profile page

apps/threeid/app/routes/$profile/index.tsx
Changes button type to switch <a> tag to <Link> on button to edit profile.
- Closes #1265
=> fix(threeid): transition on button to edit profile

platform/starbase/src/index.ts, platform/starbase/src/nodes/application/apiKeyUtils.ts, platform/starbase/src/nodes/application/index.ts, platform/starbase/src/nodes/application/schema.ts, platform/starbase/src/schema.ts
Adds functionality to generate API keys per app.
- Contributes to #1190 
```
curl -X POST \
-H 'Content-Type: application/json' \
localhost:9090/jsonrpc \
-H 'KBT-Access-JWT-Assertion: (token)' \
-d '{ "jsonrpc": "2.0", "method": "kb_appRotateApiKey", "params": { "clientId": "(clientId of existing app)" } }'
```
=> feat(starbase): Enable API key generation/rotation in Starbase

packages/openrpc/component/README.md, packages/openrpc/component/index.ts
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Closes # (issue)
- Closes # (issue)
- Closes # (issue)
- Security Fix
=> doc(openrpc): add docs for the @kubelt/openrpc package

packages/platform-clients/index.ts, packages/platform-clients/indexer.ts, platform/galaxy/src/env.ts, platform/galaxy/src/schema/resolvers/nfts.ts, platform/galaxy/wrangler.toml
creates indexer client to fetch/post nft gallery for now
=> feat(packages): export indexer client to galaxy

apps/console/app/components/SiteMenu/appSelect.tsx
Updated side menu to match Figma designs.
- Closes #1296 
- Hooked create new app button
Visually
=> feat(console): align side menu to Figma

apps/profile/app/components/nft-collection/ProfileNftCollection.tsx
Sorts collections alphabetically
- Closes #1233 
locally
=> chore(profile): sort collections alphabetically

.github/workflows/main-console.yaml, .github/workflows/main-passport.yaml, .github/workflows/main-profile.yaml, .github/workflows/next-console.yaml, .github/workflows/next-passport.yaml, .github/workflows/next-profile.yaml, .github/workflows/release-console.yaml, .github/workflows/release-passport.yaml, .github/workflows/release-profile.yaml
Splits the session salt secret by environment. Injects the correct secret, depending on environment. New secrets have already been created in GHA.
Closes #1252 
- Chore
Has not. Pipeline execution will test.
=> chore(gha): Changing secrets references for the session salt.

apps/profile/app/components/nft-collection/NftModal.scss, apps/profile/app/components/nft-collection/NftModal.tsx, apps/profile/app/routes/nfts/collection.tsx, apps/profile/app/routes/nfts/index.tsx, apps/profile/gql/nfts.graphql, platform/galaxy/src/schema/types/nfts.ts
UI improvements for profile
locally
=> feat(profile): copy tokenId in modal

apps/profile/app/components/nft-collection/ModaledNft.tsx
Minor fix on properly displaying image for token in $profile/collection
locally
=> fix(profile): not shrink image on resize

apps/profile/app/routes/account/gallery.tsx, platform/account/src/jsonrpc/middlewares/profile.ts
Expands schema validation to url and empty string
=> fix(account): adds empty string to url validation

apps/profile/app/components/accounts/PfpNftModal.tsx, apps/profile/app/components/nft-collection/NftGrid.tsx, apps/profile/app/components/nft-collection/ProfileNftGallery.tsx, apps/profile/app/components/nft-collection/ProfileNftSingleCollection.tsx, apps/profile/app/components/nft-collection/SelectableNft.tsx, apps/profile/app/routes/$profile.tsx, apps/profile/app/routes/$profile/collection.$collection.tsx, apps/profile/app/routes/$profile/gallery.tsx, apps/profile/app/routes/account/gallery.tsx, apps/profile/app/routes/account/settings.tsx, apps/profile/app/routes/account/settings/profile.tsx, apps/profile/app/routes/nfts/gallery.tsx, apps/profile/gql/nfts.graphql, platform/galaxy/src/schema/resolvers/nfts.ts, platform/galaxy/src/schema/types/nfts.ts
Nested collection in modal in `account/gallery` and `/gallery` subroute in `/$profile`
- Closes #1331
=> feat(profile): gallery page on $profile

docs/3id/index.md
=> docs(3id): Fix Mobile Docs

apps/console/app/root.tsx
=> fix(console): Fix Tabification Typo

apps/profile/app/components/accounts/PfpNftModal.tsx, apps/profile/app/components/accounts/SaveButton.tsx, apps/profile/app/components/conditional-tooltip.tsx, apps/profile/app/components/nft-collection/CollectionFilter.tsx, apps/profile/app/components/nft-collection/ModaledNft.tsx, apps/profile/app/components/nft-collection/NftGrid.tsx, apps/profile/app/components/nft-collection/ProfileNftCollections.tsx, apps/profile/app/components/nft-collection/ProfileNftGallery.tsx, apps/profile/app/components/nft-collection/ProfileNftSingleCollection.tsx, apps/profile/app/components/nft-collection/SelectableNft.tsx, apps/profile/app/components/profile/links.tsx, apps/profile/app/routes/$profile.tsx, apps/profile/app/routes/$profile/gallery.tsx, apps/profile/app/routes/$profile/index.ts, apps/profile/app/routes/account.tsx, apps/profile/app/routes/account/gallery.tsx, apps/profile/app/routes/account/settings/links.tsx, apps/profile/app/routes/account/settings/profile.tsx, apps/profile/app/routes/nfts/gallery.tsx, apps/profile/app/routes/nfts/galleryFromD1.tsx, packages/design-system/src/molecules/modal/Modal.tsx, packages/platform-clients/indexer.ts, packages/types/router.ts, platform/account/src/jsonrpc/validators/profile.ts, platform/address/src/jsonrpc/validators/profile.ts, services/indexer/src/context.ts, services/indexer/src/index.ts, services/indexer/src/queue/index.ts
ui improvements
- Closes #1359
=> chore(profile): ui improvements

apps/profile/app/components/accounts/PfpNftModal.tsx, apps/profile/app/components/nft-collection/NftGrid.tsx, apps/profile/app/routes/account/gallery.tsx
Visual fixes for `account/gallery`
=> fix(profile): text align and min-h to gallery

apps/passport/app/routes/authenticate/microsoft/callback.ts, apps/passport/app/routes/authorize.tsx, apps/passport/app/utils/cacheImageToCF.server.ts, platform/address/src/jsonrpc/validators/profile.ts
Previous authz PRs removed key functionality in MS integration callback handler. This reverts those changes.
=> fix(passport): Fix regression for MS avatar caching

packages/urns/index.ts, platform/address/src/jsonrpc/methods/setAccount.ts
Fix for encoding bugs in the URNs and setAccount
Locally, and in a mob session.
=> fix(platform): Fix for encoding bugs in the URNs and setAccount

apps/console/app/utilities/session.server.tsx, apps/passport/app/platform.server.ts, apps/passport/app/session.server.ts, apps/profile/app/routes/account/settings/links.tsx, apps/profile/app/routes/account/settings/profile/update-cover.tsx, packages/types/headers.ts, platform/address/src/constants.ts, platform/address/src/jsonrpc/methods/unsetAccount.ts, platform/address/src/jsonrpc/middlewares/parse3RN.ts, platform/galaxy/src/schema/resolvers/account.ts, platform/galaxy/src/schema/resolvers/address.ts
=> chore(platform): headers and cookies

platform/images/package.json
=> fix(images): fixes dev script

platform/galaxy/src/env.ts
Delete indexer from galaxy interface
=> fix(galaxy): no indexer

apps/profile/wrangler.toml
Updated profile URL auth vars
It hasn't.. yet.
=> fix(profile): Updated profile URL auth vars

apps/console/app/components/IconPicker/index.tsx
Checks if size limit of image/gif less than 1Mb
- Closes #1443 
=> chore(console): set image limit size

platform/address/src/jsonrpc/methods/getAddressProfile.ts, platform/address/src/jsonrpc/validators/oauth.ts, platform/address/src/jsonrpc/validators/profile.ts, platform/address/src/nodes/crypto.ts, platform/address/src/types.ts, platform/galaxy/src/schema/resolvers/address.ts
Correctly resolves addresses types on galaxy side. Adds new field to profile which isn't passed to the client since it's not specified in gql files.
- Closes #1541 
=> fix(galaxy): new field to resolve types

platform/address/src/jsonrpc/methods/getAddressProfile.ts, platform/address/src/jsonrpc/validators/oauth.ts, platform/address/src/jsonrpc/validators/profile.ts
Sets the predicate property in the schema as a default value so it is always
present.
- Manually testing sign-in process and landing on console and profile apps
=> fix(address): set the profile type predicate in the schema

apps/profile/app/routes/account/settings/profile/image-upload-url.tsx
Fixes bug with getting upload URL from new tRPC worker
- Closes #1582 
=> fix(profile): upload OG image

apps/console/app/components/Applications/Auth/ApplicationAuth.tsx, apps/console/app/components/Applications/Dashboard/ApplicationDashboard.tsx
Added copiable property to Application ID inputs
- Closes #1595 
Visually in Dashboard
As well as OAuth screen
Functionally here:
6041a62ff6e32cd2ac68c410a94ce637
6041a62ff6e32cd2ac68c410a94ce637
=> BUG(console): missing copy icon

apps/profile/app/routes/account/settings/links.tsx, packages/urns/edge.ts, platform/edges/src/db/index.ts, platform/edges/src/db/update.ts, platform/edges/src/jsonrpc/methods/updateEdges.ts
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Closes # (issue)
- Closes # (issue)
- Closes # (issue)
- Security Fix
=> feat(edges): batch upserts and txns

README.md, apps/console/app/components/InfoPanel/InfoPanelDashboard.tsx, apps/profile/app/components/FAQ/index.tsx, docs/getting-started/auth-flow.md, docs/reference/galaxy-api.md, docs/reference/passport-api.md, docs/reference/public-profile-api.md, docs/troubleshooting/faq.md
=> chore(repo): proofzero github

apps/passport/app/routes/authenticate/$address/token.tsx
The `/authorize` URL constructed was incorrect.
- Manual
=> fix(passport): authorize passport

README.md, docs/getting-started/accessing-profile-api.md, docs/getting-started/auth-flow.md, docs/getting-started/create-an-application.md
=> chore: fix typos

apps/profile/app/components/accounts/NoCryptoAddresses.tsx, apps/profile/app/components/addresses/AddressList.tsx, apps/profile/app/helpers/profile.ts, apps/profile/app/routes/account/gallery.tsx, apps/profile/app/routes/account/settings/connections/index.tsx, apps/profile/app/routes/account/settings/links.tsx, packages/design-system/src/atoms/lists/List.stories.tsx, packages/design-system/src/atoms/lists/List.tsx, packages/design-system/src/atoms/lists/ListItem.tsx, platform/address/src/jsonrpc/methods/resolveAccount.ts, platform/galaxy/src/schema/resolvers/address.ts
=> chore(profile): disable vault

apps/console/app/routes/signout.tsx, apps/console/app/utilities/session.server.tsx, apps/passport/app/routes/authenticate.tsx, apps/passport/app/routes/authorize.tsx, apps/passport/app/routes/authorize/index.tsx, apps/passport/app/routes/signout.tsx, apps/passport/app/session.server.ts, apps/passport/server.js, apps/profile/app/routes/signout.tsx, apps/profile/app/utils/session.server.tsx
=> fix(platform): signout

apps/console/app/components/Applications/ApplicationList.stories.tsx, apps/console/app/components/Applications/Dashboard/ApplicationDashboard.stories.tsx, apps/console/app/components/Applications/Dashboard/ApplicationDashboard.tsx, apps/console/app/components/Applications/LoginsPanel/LoginsPanel.stories.tsx, apps/console/app/components/Applications/LoginsPanel/LoginsPanel.tsx, apps/console/app/components/Applications/Users/ApplicationUsers.tsx, apps/profile/app/routes/account/dashboard.tsx, packages/design-system/src/assets/nested-error.svg, packages/design-system/src/pages/nested-error/NestedErrorPage.stories.tsx, packages/design-system/src/pages/nested-error/NestedErrorPage.tsx
- Closes #1651 
Creates error page for nested routes in profile and console
=> feat(apps): error for nested routes

apps/profile/app/routes/account/dashboard.tsx
Made CTA in profile dashboard mobile responsive.
Visually
=> chore(profile): mobile cta

apps/console/app/components/InfoPanel/InfoPanelDashboard.tsx
=> fix(console): meaningful text

apps/profile/app/routes/account/links.tsx
=> fix(links): layout

apps/passport/app/root.tsx
Tested with thrown response
closes #1636
=> fix(passport): useloader in error boundry

apps/profile/app/components/profile/links/links.tsx, apps/profile/app/helpers/profile.ts
Opens new tabs when clicking on link on public profile
- Closes #1667
=> fix(profile): new link tab

docs/reference/galaxy-api.md
Tweaked doc to note rate-limit on Galaxy API.
- Closes #1637
- Chore
N/A
=> chore(docs): Tweaked doc to note rate-limit on Galaxy API.

platform/access/src/nodes/access.ts
The callback function must use the transaction object for any storage operation.
- Manual
=> fix(access): fix storage transaction calls

apps/profile/app/routes/account/gallery.tsx
UI improvements as well as new feature to delete item.
- Closes #1738 
- Closes #1720 
=> feat(profile): delete nft

apps/console/package.json, yarn.lock
Adding missing flowbite-react dependency 
`yarn install` and the import statement on LoginPanel.tsx not erroring out in vscode.
=> fix(console): Adding missing depenency

platform/account/src/jsonrpc/methods/setGallery.ts, platform/account/src/jsonrpc/methods/setLinks.ts
=> fix(account): await update

apps/passport/app/components/authentication/Authentication.stories.mdx, apps/passport/app/components/authentication/Authentication.tsx, apps/passport/app/components/connect-oauth-button/index.tsx, apps/passport/app/routes/authenticate/index.tsx, apps/passport/app/routes/connect/github/index.tsx
Added a loading bar when clicking an OAuth login button. This will show a loader while /connect/index flow gets loaded.
- Closes #1782 
Added a 50ms timeout to /github/index.tsx to observe loader in action.
=> feat(passport): social login not displaying loading bar

apps/profile/app/routes/account/connections/rename.tsx
On cloudflare side the logs show the request as getting cancelled. Locally it doesn't happen. So a race condition. Trying this.
This is the test
=> bug(profile): address rename not working

apps/profile/app/helpers/profile.ts, apps/profile/app/routes/account/connections/index.tsx, apps/profile/app/routes/account/dashboard.tsx
Extracted away the mapper & used the same component as in connected accounts.
- Closes #1743 
Visually
=> bug(profile): make dashboard connected accounts match connected accounts edit page

apps/console/app/components/Applications/Users/ApplicationUsers.tsx, apps/console/app/routes/apps/$clientId/users.tsx
Adds loading spinner to users page in console
- Closes #1902 
=> chore(console): users loading

.github/workflows/main-email.yaml, .github/workflows/next-email.yaml, .github/workflows/release-email.yaml
Fixes spacing issue in GHA workflow files for email
N/A; workflow will have to run to test.
=> fix(email): Missing space in GHA workflow YAML :/

apps/passport/app/components/authentication/Authentication.tsx, apps/passport/app/routes/authenticate.tsx
- Closes #1901 
https://user-images.githubusercontent.com/635806/225310459-fc8865a2-199b-49ff-8770-4918a1df7531.mov
=> fix(passport): fix passport image panel on small screens

apps/profile/app/routes/account.tsx, apps/profile/app/routes/account/gallery.tsx, apps/profile/app/routes/account/links.tsx, apps/profile/app/routes/account/profile.tsx, apps/profile/app/types.ts, apps/profile/app/validation.ts
Introduces schema validation for ProfileKV
- Closes #1892
Manually checked all fields in `/account` subroutes
=> feat(profile): zod schema validation for KV

apps/profile/app/components/head-nav/index.tsx, apps/profile/app/components/side-nav/index.tsx, apps/profile/app/routes/account.tsx
Fixes navbar for mobile in landscape mode
- Closes #1936
Locally on browser with responsive screens
=> fix(profile): navbar on mobile landscape mode

docs/reference/passport-api.md
Userinfo endpoint reference
- Closes #1819
- Docs
N/A
=> doc(passport): Userinfo endpoint reference

apps/profile/app/components/head-nav/nav-links.tsx, apps/profile/app/components/side-nav/index.tsx, apps/profile/app/validation.ts
Minor profile schema and missing image fixes
- Closes #1986 
Checked zod schema to be able to update profile without gallery
=> fix(profile): zod schema with optional gallery and links

apps/passport/app/routes/authenticate/$clientId/email/index.tsx, apps/passport/app/routes/authenticate/$clientId/email/verify/index.tsx, apps/passport/app/routes/connect/email/otp.ts, platform/address/src/nodes/email.ts
Various OTP fixes.
- Closes #2005
- Closes #2003
Was sending OTP back and forth locally
=> fix(passport): various OTP fixes

apps/console/app/components/SiteMenu/appSelect.tsx, apps/console/app/components/SiteMenu/index.tsx
Substitutes navLink to useSubmit and fixes Applications list to show empty list of applications when the list is empty
- Closes #2015
- Closes #2016
=> fix(console): functional and ui fixes

.github/PULL_REQUEST_TEMPLATE.md
- Fixes "Closes" phrasing to cause linking of PR to issue 
- Removed template header that isn't relevant for PR templates but only issue ones.
- N/A
N/A
=> fix(gh): Fix PR template

packages/security/persona.ts
Fixes condition where `email` scope receives undefined dst urn
👀
=> fix(scopes): email scope check

apps/console/app/components/SiteMenu/index.tsx, apps/passport/app/components/SideMenu/index.tsx, packages/design-system/src/atoms/form/ReadOnlyInput.tsx, packages/design-system/src/styles/global.css, platform/starbase/src/jsonrpc/methods/getAppPublicProps.ts, platform/starbase/src/jsonrpc/validators/app.ts
- Disables scrollbars on side menu in console
- Doesn't set an empty string to redirectURI in starbase and keeps it undefined if it is
- Doesn't log you out in passport in new tab
- Removes hidden eye icon from client secret in console
- Closes #2085
- Closes #2104
- Closes #2105
It was tested visually in console against different screens
=> fix(repo): various UI/UX/DX bug fixes

packages/security/scopes.ts
=> chore(passport): Tooltip copy for connected accounts in authz screen

apps/console/app/routes/apps/$clientId/auth.tsx, apps/console/app/types.ts, apps/console/tests/console.spec.ts, apps/passport/app/routes/authenticate/$clientId.tsx, apps/passport/app/routes/authenticate/$clientId/account.tsx, apps/passport/app/routes/authenticate/$clientId/index.tsx, apps/passport/app/routes/authorize.tsx, platform/starbase/data/state/kv/FIXTURES/local-acmecorp, platform/starbase/src/jsonrpc/methods/getAppPublicProps.ts, platform/starbase/src/jsonrpc/validators/app.ts, platform/starbase/src/nodes/application.ts
- Closes #2096 
[Describe which cases you tested and their steps, if PR does not contain automated tests for them]
=> feat(passport|console): Add application privacy policy and TOS to login, continue with and authz screens

apps/console/app/components/SiteMenu/index.tsx, apps/console/app/routes/apps/$clientId.tsx, apps/console/app/routes/apps/new.tsx, apps/console/app/routes/dashboard/index.tsx, apps/passport/app/components/SideMenu/index.tsx, apps/passport/app/components/authentication/Authentication.tsx, apps/passport/app/root.tsx, apps/passport/app/routes/authorize.tsx, apps/passport/app/routes/settings.tsx, apps/profile/app/assets/site.webmanifest, apps/profile/app/root.tsx, apps/profile/app/routes/account.tsx, packages/design-system/src/atoms/pills/PrimaryPill.tsx
- Tries to address issues in #2139 
- Doesn't close because some of them need to be tested on dev
- #2139 
- This is the test
=> chore(Passport): UI Fixes

docs/reference/galaxy-api.md
=> chore(docs): remove extra colons in the bearer token syntax

apps/passport/app/routes/authenticate/$clientId/account.tsx, packages/design-system/src/molecules/auth-button/AuthButton.tsx
=> fix(passport): Continue with button display missing name

docs/getting-started/overview.md, docs/how-it-works.md, docs/platform/passport.md, docs/troubleshooting/faq.md
This PR updates the documentation by proofreading and correcting the spelling and grammar errors found.
- [How it works](https://docs.rollup.id/how-it-works)
- [Overview](https://docs.rollup.id/getting-started/overview)
- [Passport](https://docs.rollup.id/platform/passport)
- [FAQ](https://docs.rollup.id/troubleshooting/faq)
=> fix(docs) Proofread and correct spelling and grammar errors

platform/galaxy/src/schema/resolvers/address.ts, platform/galaxy/src/schema/resolvers/common.ts, platform/galaxy/src/schema/resolvers/utils/index.ts, platform/galaxy/src/schema/types/address.ts
fixes register session key method
Locally
=> fix(galaxy): register session keys

packages/types/headers.ts, packages/utils/index.ts, packages/utils/jwt.ts, platform/galaxy/src/schema/resolvers/address.ts, platform/starbase/src/jsonrpc/apiKeyExtract.ts, platform/starbase/src/jsonrpc/context.ts, platform/starbase/src/jsonrpc/ownAppsMiddleware.ts
Fixes API key set up in Starbase and Galaxy
Locally
=> fix(platform): add api key middleware

apps/passport/app/components/connect-button/ConnectButton.tsx, apps/passport/app/components/connect-oauth-button/index.tsx, apps/passport/app/routes/authenticate/$clientId/index.tsx, packages/design-system/src/molecules/auth-button/AuthButton.tsx
=> fix(passport): Lazy load wagmi on login screen

apps/console/app/root.tsx, apps/console/remix.config.js, apps/passport/app/root.tsx, apps/passport/bindings.d.ts, apps/profile/app/root.tsx, packages/design-system/src/atoms/accounts/ConnectedAccountSelect.tsx, packages/design-system/src/hooks/useTreeshakeHack.tsx
=> fix(passport): infinite loop in account select

apps/console/app/routes/apps/$clientId/auth.tsx, apps/console/app/routes/apps/$clientId/blockchain.tsx, apps/console/app/types.ts, packages/design-system/src/atoms/form/MultiSelect.stories.tsx, packages/design-system/src/atoms/form/MultiSelect.tsx, packages/design-system/src/styles/global.css, packages/security/scopes.ts
redesign of allowed scope dropdown. adds scope descriptions
- Closes #2154
Storybook/console `/auth`page
=> feat(console): Add scope description to the Allowed scope dropdown

packages/design-system/src/atoms/form/MultiSelect.tsx
Fixes scope deletion and form change
Manually
=> fix(console): changes form when delete scope

apps/console/app/components/AppBox/index.tsx, apps/console/app/components/Applications/ApplicationList.tsx, apps/console/app/components/Applications/ApplicationListItem.tsx, apps/console/app/components/SiteMenu/index.tsx, apps/console/app/routes/apps/new.tsx, apps/console/app/routes/dashboard/index.tsx, apps/passport/app/components/SideMenu/index.tsx, packages/design-system/src/atoms/form/MultiSelect.tsx
- Fixes loading bar when navigate to app from console dashboard
- Fixes loading bar when creating new app
- Fixes size of side menu when there're too many apps in console
- Closes #2280
By clicking on apps from console dashboard
=> fix(console): loading bar on redirect to app from dashboard

platform/starbase/src/nodes/application.ts
Missing `await` operator for a storage operation call.
Throws an internal server error if the application object is not found in the
update method call.
=> fix(starbase): missing `await` operator

apps/console/app/components/DocumentationBadge/index.tsx, apps/console/app/components/IconPicker/index.tsx, apps/console/app/components/SiteHeader/index.tsx, apps/console/app/routes/apps/$clientId/blockchain.tsx, apps/console/app/routes/apps/$clientId/users.tsx, packages/design-system/src/atoms/buttons/common.tsx, packages/design-system/src/atoms/email/EmailSelect.tsx, packages/design-system/src/atoms/form/Input.tsx, packages/design-system/src/atoms/form/MultiSelect.tsx, packages/design-system/src/atoms/panels/Panel.tsx
Improves UI in console
- Closes #2284 
Visually in console
=> fix(console): ui

packages/design-system/src/atoms/dropdown/DropdownSelectList.tsx
=> fix(design-system): type check

apps/console/app/routes/apps/$clientId/designer.beta.tsx, platform/email/emailOtpTemplate.ts
Remove aspect ratios for designer
- Closes #2408
https://github.com/proofzero/rollupid/assets/33105890/6b2c8ca9-5a88-4965-ba22-eb0080998095
=> fix(console): remove aspect ratios in designer

apps/passport/app/root.tsx
Removes unnecessary comment from passport root component
=> fix(passport): remove comment from returned component

apps/console/app/routes/__layout/gnillib/index.tsx, apps/passport/tests/passport.spec.ts, packages/design-system/src/molecules/modal/Modal.tsx
Implement Figma frames and integrate with Stripe abstraction
- Closes #2403
In console under `gnillib` route
- purchase entatlements
- remove some of them
=> feat(console): Billing & Invoicing - remove entitlements frame

apps/console/app/routes/apps/$clientId/designer.beta.tsx, apps/console/package.json, yarn.lock
- Fixed darkmode in preview
- Added `dark` class to wrapper element based on toggle
- Closes #2409 
- Toggled
=> fix(console): darkmode broken in preview

platform/email/emailTemplate.ts
Fixes subject for email notifications
=> fix(email): subject for notifications

platform/email/emailTemplate.ts, platform/email/wrangler.toml
Added subject to reconciliation e-mails
=> fix(billing): reconciliation email subject

apps/console/app/components/SiteMenu/index.tsx, apps/console/app/routes/__layout/groups/index.tsx
- Hides `Groups` menu item
- Adds empty state for group index page
- Visual
=> chore(groups): empty state and hide menu item

apps/console/app/routes/apps/$clientId/billing.tsx
Aligned app plan page to new Figma design
- Closes #2497 
Visual
=> chore(console): Service Plan Page Improvement

apps/console/app/routes/__layout/billing/index.tsx
- Show the gauge but 0 assigned
- Closes #2494
=> fix(console): Entitlements gauge not shown when none assigned

apps/passport/app/routes/authenticate/$clientId/email/index.tsx
Doesn't generate OTP twice in passport
Locally
=> fix(passport): otp generation

apps/console/app/routes/apps/$clientId/domain.tsx
- Added required parameter to early access panel for custom domains
=> fix(console): domain upgrade button

apps/console/app/components/SiteMenu/index.tsx
- Added configurable menu item properties for app menu
- Added lock icon for items gated behind PRO plan
- Added hourglass icon for items in early access
- Closes #2498 
- Visual using two applications
- One in FREE plan
- One in PRO plan
- Toggle between
=> chore(console): Add Indicators to Sidebar Navigation

apps/console/app/routes/__layout/billing/index.tsx, apps/console/app/routes/__layout/billing/plans.ts, apps/console/app/routes/apps/$clientId/billing.tsx
=> chore(billing): update plan feature colors

apps/console/app/routes/__layout/billing/index.tsx, apps/console/app/routes/__layout/billing/update.tsx, apps/console/app/routes/apps/$clientId/audience.tsx, apps/console/app/routes/apps/$clientId/billing.tsx, packages/design-system/src/atoms/spinner/Spinner.tsx, packages/design-system/src/atoms/toast/ToastWithLink.tsx, packages/design-system/src/molecules/modal/Modal.tsx
[Provide a more detailed description of the change]
- Closes #2503
[Describe which cases you tested and their steps, if PR does not contain automated tests for them]
=> chore(console): CTA for purchased entitlements

apps/passport/app/routes/authenticate/$clientId/index.tsx
Doesn't proceed with metamask login if there's no internet connection
- Closes #2294
As described in the issue
=> fix(passport): Connect with Wallet with no internet

packages/design-system/src/molecules/email-otp-validator/EmailOTPValidator.tsx, platform/email/emailTemplate.ts
Closes two UI tickets related to OTP
- Closes #2534 
- Closes #2577
Locally and email OTP was tested in DEV
=> fix(apps): email OTP logo+email OTP overflow

apps/console/app/components/DeleteAppModal/DeleteAppModal.tsx, apps/console/app/components/RotateCredsModal/RotateCredsModal.tsx, apps/console/app/routes/__layout/billing/index.tsx, apps/console/app/routes/__layout/spuorg/$groupID/index.tsx, apps/console/app/routes/__layout/spuorg/index.tsx, apps/console/app/routes/apps/$clientId/billing.tsx, apps/console/app/routes/apps/$clientId/designer.tsx, apps/console/app/routes/apps/$clientId/domain.tsx, apps/passport/app/components/applications/claims.tsx, apps/passport/app/components/settings/accounts/DisconnectModal.tsx, apps/passport/app/routes/settings/accounts/index.tsx, apps/passport/app/routes/settings/advanced.tsx, apps/profile/app/components/accounts/PfpNftModal.tsx, apps/profile/app/components/accounts/UnsavedChangesModal.tsx, apps/profile/app/components/nfts/modal/index.tsx, packages/design-system/src/atoms/dropdown/DropdownSelectList.tsx, packages/design-system/src/molecules/modal/Modal.tsx
Makes the close button inline with the modal heading
- Closes #2573
Visual changes were tested locally
=> chore(modal): make the close button inline with the modal heading

apps/console/app/components/AppBox/index.tsx, apps/console/app/components/Applications/ApplicationListItem.tsx, apps/console/app/components/SiteMenu/appSelect.tsx, packages/design-system/src/atoms/pills/Pill.tsx
Creates `PRO` indicators for applications
- Closes #2537
Visual changes were tested locally
=> chore(console): pro indicators

apps/console/app/routes/__layout/billing/webhook.tsx, apps/console/app/routes/__layout/spuorg/$groupID/invite.tsx, apps/passport/app/root.tsx, apps/passport/app/routes/authenticate/$clientId/email/verify.tsx, apps/passport/app/routes/authorize.tsx, apps/passport/app/routes/connect/apple/callback.ts, apps/passport/app/routes/connect/discord/callback.ts, apps/passport/app/routes/connect/github/callback.ts, apps/passport/app/routes/connect/google/callback.ts, apps/passport/app/routes/connect/microsoft/callback.ts, apps/passport/app/routes/connect/twitter/callback.ts, apps/passport/app/routes/settings/applications/$clientId/revoke.tsx, packages/utils/analytics.ts, platform/address/src/jsonrpc/methods/resolveAccount.ts, platform/starbase/src/jsonrpc/methods/publishApp.ts, platform/starbase/src/jsonrpc/methods/setAppPlan.ts
Introduces events to set initial user journey dashboard
- Closes #1751
TBD
=> feat(platform): User journey dashboard

apps/passport/app/routes/index.tsx
=> fix(passport): removes nested <html> tag

apps/console/app/root.tsx, apps/console/app/routes/apps/$clientId/designer.tsx, apps/console/app/routes/index.tsx, apps/passport/app/root.tsx, apps/passport/app/routes/authenticate/$clientId.tsx, apps/passport/app/routes/authenticate/$clientId/index.tsx, apps/passport/app/routes/index.tsx, platform/starbase/src/jsonrpc/methods/getOgTheme.ts, platform/starbase/src/jsonrpc/methods/setOgTheme.ts, platform/starbase/src/jsonrpc/router.ts, platform/starbase/src/jsonrpc/validators/app.ts, platform/starbase/src/nodes/application.ts
Creates Open Graph tab with the ability to set up OG data for the app in Designer.
- Closes #2535 
TBD
=> feat(console): Designer OG data

apps/passport/app/root.tsx
Fixes error when `data` in `undefined` in `meta` function in passports' `root.tsx`
=> fix(passport): fixes issue when data is undefined

apps/console/app/routes/onboarding/index.tsx, platform/email/emailTemplate.ts
- Fixes onboarding copy and links
- Fixes email template so OTP code extraction for local/test envs works again.
- N/A
Logged in to Console with new identity and connected new email (to test local OTP code extraction)
=> fix(console): Onboarding copy fix and OTP code local fix

apps/passport/app/routes/authenticate/$clientId/webauthn/register.tsx
Fixes:
- Round corners around registration box
- Registration submission button colour.
Note: third issue in ticket having to do with auto-zoom is being moved to a discussion first, as it affects other areas of the system
- Closes #2668
Visual tests on the registration screen.
=> fix(passport): Passkeys CSS fixes

apps/console/app/routes/apps/$clientId/index.tsx
- `Galaxy GraphQL API Key` => `Galaxy API`
- Removed Smart Wallet Panel
- Closes #2647
=> chore(console): App Dashboard Cleanup

apps/passport/app/utils/authorize.server.ts, packages/design-system/src/atoms/info/Info.tsx, packages/design-system/src/templates/authorization/Authorization.tsx, packages/design-system/src/templates/authorization/ScopeIcon.tsx
=> fix(passport): Tweaks to authz screen

apps/console/app/routes/apps/$clientId/designer.tsx
- Fix a hook after a conditional preventing designer from working as intended
- On `dev` it errored out
- Locally errored out
- Locally fixed
- Dev soon
=> fix(designer): hook after conditional

packages/design-system/src/atoms/info/Info.tsx, packages/design-system/src/templates/authorization/Authorization.tsx
- Added a nested conditional to the already existing conditional for displaying info box;
- In the future we might consider creating a better component structure for handling edge cases.
- Closes #2706
=> chore(passport): Apple hidden email not reachable by third-parties

.github/workflows/main-emailinbounder.yaml
Env-specific params missing from GHA workflow, for Dev, are now added.
- N/A
Merge will be the test.
=> fix(CI): Fixes deploy command params for emailinbounder-dev

platform/emailinbounder/src/index.ts
Tweaks the from field of relayed emails to note that it's a relayed email. Also, sets the reply-to field with the original sender.
- Closes #2783
Send email to hidden address. Note the name of the sender, as well as reply-to address in relayed email.
=> chore(emailinbounder): Tweaks sender string and sets reply-to address.

.github/workflows/main-emailinbounder.yaml, .github/workflows/next-emailinbounder.yaml, .github/workflows/release-emailinbounder.yaml
Replaced GHA workflow var with wrangler one
- N/A
N/A
=> fix(emailinbounder): Replaced GHA workflow var with wrangler one

CONTRIBUTING.md
Changing the name and link to the social network
[Provide a more detailed description of the change]
- Closes #1
[Describe which cases you tested and their steps, if PR does not contain automated tests for them]
=> Docs: Update CONTRIBUTING
