- src/main/com/kubelt/ddt/cmds/wallet/init.cljs
- src/main/com/kubelt/lib/wallet/node.cljs
Fixes an error that occurred when making a CLI wallet directory when the parent `.config/ddt` directory didn't already exists. Recursively creates the wallet directory and specifies the config directory mode as well.
> fix(ddt): recursively create config wallet path

- bb.edn
- packages/sanity-plugin-kubelt/src/actions/KubeltPublishAction.tsx
- packages/sanity-plugin-kubelt/src/badges/KubeltNamedBadge.tsx
- packages/sanity-plugin-kubelt/src/resolvers/badgeResolver.ts
- packages/sanity-plugin-kubelt/src/services/semanticService.test.ts
This is a long-coming removal of code as the initial idea was to append properties to objects to be marked in the Kubelt system. This idea has been put on hold and the final shape will look very much differently.
Closes #164 
> CHORE(Sanity): Remove kItem definition dependency

- src/main/com/kubelt/ddt/cmds/p2p/authenticate.cljs
- src/main/com/kubelt/ddt/cmds/p2p/verify.cljs
- src/main/com/kubelt/ddt/cmds/sdk/core/authenticate.cljs
- src/main/com/kubelt/ddt/cmds/sdk/core/register.cljs
Properly configures `core` argument to several `ddt` commands as being of `string` type. This prevents "naked" core addresses of the format `0x<hex string>` from being parsed by the CLI framework as integers.
Incidentally updates an incorrect doc string for a command.
> fix(ddt): treat core names as strings rather than parsing as integers

- src/main/com/kubelt/ipfs/client.cljc
- src/main/com/kubelt/lib/http/browser.cljs
- src/main/com/kubelt/lib/http/jvm.clj
- src/main/com/kubelt/lib/http/node.cljs
- src/main/com/kubelt/proto/http.cljc
- src/test/lib/http/request_test.cljc
Clean up the protocol for making HTTP requests, standardizing on a promise-based approach. Note that JVM works a bit differently but isn't a platform target as of yet; that implementation is sometimes useful for REPL-based development.
- will be fleshed out in further work
> chore(sdk): work on cleaning up HTTP client

- bb.edn
Removed the `test:dapp:release` task in a previous PR (https://github.com/kubelt/kubelt/pull/294) which still runs on merges.
This task runs the compilation steps in parallel, then runs the server start and testing stages one after the other.
> chore(dapp): Re-add `test:dapp:release` which still runs on merges

- www/content/en/showcase/paymi/index.md
Just a doc fix to solve that [http(s)://paymi.com/](http://paymi.com/) doesn't work in my browser nor my terminal
```
wget https://paymi.com/
--2022-04-11 21:13:13--  https://paymi.com/
Resolving paymi.com (paymi.com)... 75.2.60.5, 99.83.190.102, 75.2.70.75
Connecting to paymi.com (paymi.com)|75.2.60.5|:443... connected.
ERROR: no certificate subject alternative name matches
requested host name ‘paymi.com’.
To connect to paymi.com insecurely, use `--no-check-certificate'.
```
> Use www.paymi.com instead of paymi.com

- dapp/src/dapp/components/web3_modal.cljs
- dapp/src/dapp/pages/dashboard.cljs
- dapp/src/dapp/wallet.cljs
- Fixes modal not popping up when trying to connect wallet
- Cleans up the code from hooking up the authentication.
- Refactor's web3modal into its own component namespace
- Parameterize modal config options for using `testnet` or for general testing
- Fixed the flow so that the `authenticate!` promise is resolved
Testing this was tricky. Need to figure out a way to mock the auth or do testing in re-frame. Still thinking about this. Going to introduce it in a later PR.
https://user-images.githubusercontent.com/24436662/163026815-d0d0eca6-fd1d-4977-9722-f686a97a0c19.mov
> feat(dapp): Update web3modal style to match mocks + refactor into own component ns

- src/main/com/kubelt/ddt/cmds/jwt/sign.cljs
- src/main/com/kubelt/ddt/cmds/sdk/core/authenticate.cljs
- src/main/com/kubelt/ddt/cmds/wallet/init.cljs
- src/main/com/kubelt/lib/jwt.cljc
- src/main/com/kubelt/lib/p2p.cljs
- src/main/com/kubelt/sdk/v1/core.cljs
- src/test/lib/jwt_test.cljc
- uses wallet address as the name of the core to authenticate instead
- callers should supply a `.catch()` to handle the possible occurrence of errors
- see `ddt sdk core authenticate` command for an example
- we now keep wallets under XDG "data" directory
- requires creating a new wallet for testing, or to relocate old wallet to new location
- the principal user of that code is mothballed so future PR will remove more code and add back some tests
> feat(sdk): store decoded JWT in system map

- dapp/resources/public/images/default-avatar.svg
- dapp/src/dapp/components/header.cljs
- dapp/src/dapp/pages/dashboard.cljs
- dapp/src/dapp/wallet.cljs
- src/main/com/kubelt/lib/jwt.cljc
- src/main/com/kubelt/sdk/v1/core.cljs
- Update usage of `authenticate!` event to properly resolve the promise
- Update SDK `logged-in?` function to check one nested level deeper for appropriate token data
- Add frontend `logged-in?` state driven by SDK function which returns true when a wallet is logged in
Connected a wallet several times via Metamask to ensure all data is present. Have to figure out a way to mock pando responses as well as SDK calls when testing with re-frame. To be addressed in a future PR.
https://user-images.githubusercontent.com/24436662/163258573-f4ca9571-77db-41e8-8c51-1cfa7a0961e9.mov
> feat(dapp): Finish auth-flow work with decoded JWT stored in re-frame app-db

- dapp/src/dapp/components/header.cljs
- dapp/src/dapp/components/web3_modal.cljs
- dapp/src/dapp/pages/dashboard.cljs
- dapp/src/dapp/wallet.cljs
Add ability to disconnect wallet after connecting. Wallet can be connected and disconnected several times.
For now, it has only been tested visually. Once we can mock these events in our re-frame testing framework, we can add tests for connect and disconnect. 
https://user-images.githubusercontent.com/24436662/163842881-30abab71-56ae-45dc-b3b1-115fd3e1d920.mov
> feat(dapp): Implement wallet disconnect

- src/main/com/kubelt/ddt/cmds/path/cache.cljs
- src/main/com/kubelt/ddt/cmds/path/config.cljs
- src/main/com/kubelt/ddt/cmds/path/data.cljs
- src/main/com/kubelt/ddt/cmds/path/log.cljs
- src/main/com/kubelt/ddt/cmds/path/temp.cljs
After recent changes to standard directory locations, these utility commands needed to be updated.
> fix(ddt): update path commands to output correct paths

- src/main/com/kubelt/ddt/cmds/sdk/init.cljs
- src/main/com/kubelt/ddt/cmds/wallet/sign.cljs
- src/main/com/kubelt/ddt/options.cljs
- src/main/com/kubelt/lib/config.cljs
- src/main/com/kubelt/lib/init.cljc
- src/main/com/kubelt/spec/config.cljc
- src/test/lib/config_test.cljs
Rename some of the keys in the`init` options map for consistency:
> chore(sdk): rename options for consistency

- .github/workflows/develop.yaml
- dapp/src/dapp/core.cljs
- dapp/src/dapp/wallet.cljs
- dapp/test/dapp/integration/auth_test.cljs
- shadow-cljs.edn
- src/main/com/kubelt/lib/http/browser.cljs
- src/main/com/kubelt/lib/wallet/node.cljs
- src/main/com/kubelt/lib/wallet/shared.cljc
- Bumps some dev dependencies with new versions
- Allows `random-wallet` to be used from `:browser` targets
- Tests generated wallet against ETH `testnet` and authenticates with cloudflare-worker running locally
- Tests disconnecting via the dapp's re-frame event
- Runs on CI with private container from the Kubelt GH Container Registry
Closes https://github.com/kubelt/kubelt/issues/317
> chore(dapp): Add auth test for wallet authenticate/disconnect via dapp

- src/main/com/kubelt/spec/config.cljc
- Adapt sdk config spec to work with malli.generator
To try it:
```clojure 
(malli.generator/generate com.kubelt.spec.config/config)
;; 
{:ipfs.read/scheme :http,
:ipfs/write "/ip4/127.0.0.1/tcp/5001",
:ipfs.write/scheme :https,
:p2p/multiaddr "/ip4/127.0.0.1/tcp/5001"}
```
> Add default multiaddr malli.generator in cljs

- src/main/com/kubelt/ddt/cmds/wallet.cljs
- src/main/com/kubelt/ddt/cmds/wallet/import.cljs
- src/main/com/kubelt/ddt/cmds/wallet/init.cljs
- src/main/com/kubelt/ddt/prompt.cljs
- src/main/com/kubelt/lib/error.cljc
- src/main/com/kubelt/lib/promise.cljs
- src/main/com/kubelt/lib/wallet.cljc
- src/main/com/kubelt/lib/wallet/node.cljs
Use @ethersproject/wallet and https://docs.ethers.io/v5/api/signer/#Wallet.fromMnemonic to retrieve wallet, then we store it encrypted following current `com.kubelt.lib.wallet.node/init` approach
we are adding to ddt this new `wallet import` command, being `<name>` the name of the local wallet-id imported
Closes #353
1. generate ddt executable script with   `bb build:ddt:develop`
2. try new command with `node ddt.js wallet import example`  
3. `node ddt.js sdk wallet ls` returns the new wallet on the list 
```
-> default
-> example
-> juan
```
4. then using the wallet imported  `node ddt.js sdk core authenticate -w example` ... returns the sdk initialised
> feat(ddt): add support for importing wallets

- .github/workflows/develop.yaml
Since the `dapp` tests are essentially integration tests now, they should run on each PR to `main` before merging.
> chore(all-modules): Run dapp integration tests on each PR

- .github/workflows/develop.yaml
- bb.edn
Disabling broken builds due to downstream changes with Cloudflare Worker. 
To be enabled again once SDK has caught up.
> chore(all-modules): Disable dapp tests until JSON RPC is ready

- .gitignore
- project.clj
In order to use the SDK as a dependency via `shadow-cljs`, it is simpler to call `lein install` and build against it.
For CLJS browser apps, they would need to all the following in their compiler options map to have the SDK work as intended:
```
{:compiler-options
{:reader-features #{:browser}
...}}
```
Eventually this JAR can be used as an artifact to build and test other products that are created.
> feat(sdk): Use project.clj to build JAR for CLJ/CLJS apps

- src/main/com/kubelt/lib/error.cljc
- src/main/com/kubelt/spec/error.cljc
Rework `conform*` to avoid nested let, avoid capture, and add error checking.
> chore(sdk): refactor and add error checking in conform*

- src/main/com/kubelt/ddt/util.cljs
Minor ddt adaptation to work with camel case rpc method names
eg: `:kb:getConfig` 
before these changes path was `[:kb :getConfig]` but we needed `[:kb :get-config]`
> Adapt camel case rpc method names

- src/dev/.gitignore
- src/dev/user.cljc
- src/main/com/kubelt/lib/http/jvm.clj
- src/main/com/kubelt/rpc.cljc
- src/main/com/kubelt/rpc/request.cljc
- src/main/com/kubelt/rpc/schema/expand.cljc
- src/main/com/kubelt/rpc/schema/fs.cljc
- src/main/com/kubelt/rpc/schema/parse.cljc
- src/main/com/kubelt/rpc/schema/validate.cljc
- src/main/com/kubelt/rpc/schema/zip.cljc
- src/main/com/kubelt/spec/core/config.cljc
- src/main/com/kubelt/spec/core/config/general.cljc
- src/main/com/kubelt/spec/core/config/security.cljc
- src/main/com/kubelt/spec/openrpc/component.cljc
- src/main/com/kubelt/spec/rpc.cljc
- src/main/com/kubelt/spec/rpc/schema.cljc
When loading a schema for use by the client, references are now expanded inline to make later processing easier.
Other changes:
- when vector is supplied, parameters are matched positionally
- when map is supplied, keys are parameter name and map to corresponding value
> feat(sdk): improve SDK schema expansion

- .gitignore
simple folder git ignore
I use to set a [roam](https://www.orgroam.com/) system inside clojure repos thus using org-mode + babel i can do literate programming (using same CIDER repl connection/session to eval repo code) there with personal documentation purposes ... so this PR change is to don't track personal dev settings
> Ignore roam folder

- src/main/com/kubelt/rpc/schema/util.cljc
Memoizes the `rpc.schema.util/lookup` fn that takes a `$ref` and an edn schema and (possibly recursively) looks up the referenced definition.
> feat(rpc): memoize $ref lookup fn

- bb.edn
- shadow-cljs.edn
- src/main/com/kubelt/rpc.cljc
- src/main/com/kubelt/rpc/schema.cljc
- src/test/com/kubelt/rpc/schema_test.cljs
- [FIX: Use of undeclared Var com.kubelt.lib.error/conform*](https://github.com/kubelt/kubelt/runs/6600348899?check_suite_focus=true#step:8:379)
```
------ WARNING #1 - :undeclared-var --------------------------------------------
File: /home/runner/work/kubelt/kubelt/src/main/com/kubelt/rpc/schema.cljc:30:5
--------------------------------------------------------------------------------
27 |      (schema client prefix schema-doc defaults)))
28 | 
29 |   ([client prefix schema-doc options]
30 |    (lib.error/conform*
-----------^--------------------------------------------------------------------
Use of undeclared Var com.kubelt.lib.error/conform*
--------------------------------------------------------------------------------
.....
```
- [Fix node test output …
> Compilation and test fixes

- src/main/com/kubelt/rpc/schema/util.cljc
Turns out that `alter-var-root` doesn't exist in CLJS (oops). Hide it away using conditional reader.
> fix(rpc): only use alter-var-root in CLJ

- src/main/com/kubelt/rpc/schema/util.cljc
Following this answer https://stackoverflow.com/a/57023111
``` 
------ WARNING #1 - :redef-in-file ---------------------------------------------
File: /home/runner/work/kubelt/kubelt/src/main/com/kubelt/rpc/schema/util.cljc:73:10
--------------------------------------------------------------------------------
70 |       (recur components ref-path ref-val))))
71 |
72 | #?(:clj (alter-var-root #'lookup memoize)
73 |    :cljs (def lookup (memoize lookup) ))
----------------^---------------------------------------------------------------
lookup at line 59 is being replaced
```
> Fix :redef-in-file

- packages/sdk-clj/.gitignore
- packages/sdk-cljs/.gitignore
We have some utility scripts in our package directories for generating `project.clj` files as an aid to publishing artifacts; `shadow-cljs` user guide recommends using `lein` to that end. This just updates a couple of `.gitignore` files to ignore those generated files.
> chore: add project.clj to .gitignore

- src/main/com/kubelt/ddt/cmds/rpc/call.cljs
- src/main/com/kubelt/ddt/cmds/rpc/core.cljs
- src/main/com/kubelt/ddt/cmds/rpc/core/config/get.cljs
- src/main/com/kubelt/ddt/cmds/rpc/core/config/set.cljs
- src/main/com/kubelt/ddt/cmds/rpc/core/profile.cljs
- src/main/com/kubelt/ddt/cmds/rpc/core/profile/get.cljs
- src/main/com/kubelt/ddt/cmds/rpc/core/profile/set.cljs
- src/main/com/kubelt/lib/rpc.cljs
- src/main/com/kubelt/rpc/request.cljc
- src/test/com/kubelt/lib/test_utils.cljs
- src/test/com/kubelt/rpc/auth_test.cljs
- src/test/com/kubelt/rpc/profile_test.cljs
- src/test/com/kubelt/rpc/schema_test.cljs
- src/test/com/kubelt/rpc/test_commons.cljs
> RPC core get/set profile support

- src/main/com/kubelt/lib/json.cljc
- src/main/com/kubelt/rpc/request.cljc
- src/test/com/kubelt/rpc/test_commons.cljs
Don't use transit in json generation for rpc calls
Example data generated:
with transit
```
[\"^
\",\"~:id\",\"e12636e0-b6ff-4118-943b-e66450dfc57e\",\"~:jsonrpc\",\"2.0\",\"~:method\",\"kb_get_profile\",\"~:params\",[\"~#list\",[]]]
```
without transit
`{\"id\":\"6f17f4d8-429c-4b70-a842-5d0c7cf3d884\",\"jsonrpc\":\"2.0\",\"method\":\"kb_get_profile\",\"params\":[]}`
[There were already failing tests](https://github.com/kubelt/kubelt/runs/6724824810?check_suite_focus=true#step:8:391) ... with this change we'll have them happy again
> Fix bug with rpc calls

- package-lock.json
I noticed that after recent changes to dependencies, the `package-lock.json` file wasn't up to date. Ran `npm i` to freshen it.
> chore: update root package-lock.json

- project.clj
Clojars only supports groupId's with specific formats. In our case, we have `com.kubelt`.
See: https://github.com/clojars/administration/issues/260
> chore(sdk): Update groupId for Maven to publish to Clojars

- .github/workflows/ref-docs.yaml
Update to the latest version of Clojure CLI in `ref-docs` flow.
> chore(gha): update CLI to 1.11.0.1113 in ref-docs flow

- .github/workflows/develop.yaml
- .github/workflows/ref-docs.yaml
- deps.edn
- shadow-cljs.edn
- src/main/com/kubelt/kbt.cljs
Extract dependencies from `shadow-cljs.edn` and migrate them into `deps.edn`. This helps us to avoid overlapping sets of dependencies and possible discrepancies.
- update GHA `develop` workflow:
- removes `turtlequeue/setup-babashka@v1.3.0` which only provides `babashka`
> chore(sdk): use deps.edn to define shadow-cljs dependencies

- .github/workflows/next.yaml
- .github/workflows/release.yaml
Updates the `next` and `release` workflows to install Clojure and babashka using a single action. Clojure is now required as it is used in the invocation of `shadow-cljs` (now that we keep our dependencies in `deps.edn`).
> fix(gha): update next and release workflows

- .github/workflows/develop.yaml
- .github/workflows/next.yaml
- .github/workflows/release.yaml
Improve readability of pipeline configuration by using a node `lts/*` version specifier instead of `'16'` to indicate the version of node that we rely on.
> chore(gha): specify node version as lts/gallium

- packages/sdk-js/__tests__/api-v1.js
- src/main/com/kubelt/lib/config.cljs
- src/main/com/kubelt/lib/config/util.cljc
- src/main/com/kubelt/sdk/v1.cljs
Adds some JavaScript tests of SDK initialization where we supply various subsets of configuration options, e.g. connection details for p2p, IPFS read and write nodes, etc. Fixes an issue in the conversion of the JS configuration object into a CLJ(S) configuration map so that the results conform to our schema. Specifically, some configuration values provided in JavaScript (e.g. `{"ipfs.read/scheme": "http"}`) require that the value be converted to a keyword to conform to our config schema.
> fix(sdk): improve JS handling of SDK init options

- .github/workflows/develop.yaml
- .github/workflows/next.yaml
- .github/workflows/ref-docs.yaml
- .github/workflows/release.yaml
- deps.edn
Update remaining build pipelines to newer version of `setup-clojure` action, update Clojure to `1.11.1.1129`, and update `shadow-cljs` to `2.19.3`.
> chore(gha): update build pipelines and tooling

- dapp/test/dapp/sdk_test.cljs
- src/main/com/kubelt/lib/storage/browser.cljs
- src/main/com/kubelt/lib/storage/node.cljs
- src/main/com/kubelt/sdk/v1.cljs
- src/main/com/kubelt/sdk/v1/oort.cljs
- src/test/com/kubelt/rpc/auth_test.cljs
In [com.kubelt.lib.config.sdk/options](https://github.com/kubelt/kubelt/blob/v1-options-and-restore-fixes/src/main/com/kubelt/lib/config/sdk.cljc#L26) we use [(lib.vault/tokens (:crypto/session sys-map))](https://github.com/kubelt/kubelt/blob/v1-options-and-restore-fixes/src/main/com/kubelt/lib/vault.cljc#L25) that expects the map contains a `:com.kubelt/type :kubelt.type/vault`
Changes added to fix the problem here https://github.com/kubelt/kubelt/pull/487/files#diff-3ef5211db2f5c7b23d28d4e1d7594b2e800417447163e2c5bf5cedf12891c592
[browser](https://github.com/kubelt/kubelt/blob/v1-options-and-restore-fixes/src/main/com/kubelt/lib/storage/browser.cljs#L40) and [node](https://github.com/kubelt/kubelt/blob/v1-options-and-restore-fixes/src/main/com/kubelt/lib/storage/node.cljs#L43) impls …
> v1/options and v1/restore fixes

- .github/workflows/develop.yaml
- src/main/com/kubelt/ddt/cmds/rpc/call.cljs
- src/main/com/kubelt/ddt/cmds/rpc/oort/config/set.cljs
- src/main/com/kubelt/lib/rpc.cljs
- src/test/com/kubelt/rpc/nfts_test.cljs
- src/test/com/kubelt/rpc/profile_test.cljs
_(starting on https://github.com/kubelt/kubelt-oort/pull/115 we can get 401 status responses from rpc calls)_
So far sdk is more optimistic than it should 
https://github.com/kubelt/kubelt/blob/feat%2Fclaim%2Fadd-env-variables/src/main/com/kubelt/lib/rpc.cljs#L32
Changes in this PR allows FE can eval http status and react accordingly
> Rpc call returns whole http response

- three-id/src/provider/web3.ts
- three-id/src/screens/Auth.tsx
- three-id/src/screens/Landing.tsx
- three-id/src/screens/Layout.tsx
Added localStorage for w3conn
Snapped button to max width
Removed web3modal and replaced it with some observables. The funnel should now remember accounts, react to account disconnect events and preserve signature in the same session (without refresh). Still quirks with multiple accounts and switching / signing between them.
Closes https://github.com/kubelt/three-id/issues/86
> FEAT(claim): remove web3modal

- bb/com/kubelt/dot_env.clj
- three-id/bb.edn
Generate a `.env` during build containing target environment-specific values. Specifically, for now we set:
- `OORT_HOST`
- `OORT_PORT`
- `OORT_SCHEMA`
> feat(3iD): inject compile-time constants

- three-id/src/provider/web3.ts
Browsers without an ethereum window object would try to gauge whether metamask is present, thus throwing an exception. This should be fixed now.
Closes https://github.com/kubelt/three-id/issues/91
> BUG(Landing): Non-web3 browser exception

- three-id/bb.edn
- three-id/package-lock.json
- three-id/package.json
- three-id/worker/.gitignore
- three-id/worker/src/index.js
- three-id/worker/wrangler.toml.example
Removes some deployment configuration relating to the "SITE" application.
NB: if you have a personal development environment please:
- remove `-SITE` worker and KV store
- rename remaining service to `three-id`
- rename remaining KV store to `three-id-APP`
> chore(3iD): remove "site" deployment configuration

- three-id/src/provider/web3.ts
> When the user gets to the gate (screen 2C) and clicks "Try Different Wallet" they are sent back to 2A. When they then select Metamask the flow does not re-start. They should be asked to re-connect / re-sign the message.
References https://github.com/kubelt/three-id/issues/92
> BUG(3iD): Polish Tracker - Clear account

- .github/workflows/next.yaml
- bb.edn
- three-id/bb.edn
> fix(gha): update next pipeline

- three-id/bb.edn
Add a delay before running smoke tests as it can take time for published assets to become available. Also enables extra logging when running in a GHA workflow.
> feat(gha): make workflows more verbose, delay before smoke test

- .github/workflows/next.yaml
- three-id/bb.edn
- three-id/package-lock.json
- three-id/package.json
Updates a few dependencies:
Also tweaks the `next` workflow, `three-id` job:
> chore(3iD): update deps, tweak next workflow

- three-id/src/App.tsx
- three-id/src/analytics/datadog.ts
This changeset is concerned with activating Data Dog's mechanism for recording user sessions. Once activated, it should hook itself into browser events and create an analytics funnel which can be then used to build dashboard informing us of user activity and / or errors.
Closes https://github.com/kubelt/three-id/issues/96
> FEAT(DD): RUM session setup

- three-id/package-lock.json
- three-id/package.json
Upgrades a couple of dependencies, and downgrades one via the command:
```shell
$ npx expo doctor --fix-dependencies
```
> chore(3iD): update (and downgrade) deps

- three-id/src/App.tsx
We're enabling path navigation for web interfaces; this will have the effect of allowing us to implement features such as /profile/:id or /mint. For current sprint, it's a requirement that we are able to visit the mint page by url. Profile is probably also in this category.
Closes #555
> CHORE(Three-id): Add navigation by path on web

- bb/com/kubelt/cloudflare/client/zone.clj
- three-id/bb.edn
Enable cache purging when deploying to staging environment. Uses the Cloudflare "Purge Files by URL" API call in order to only remove files with the appropriate prefix.
> chore(3iD): purge URLs by environment

- three-id/bb.edn
Extracts the host name from deployment URL, as required when doing deployments to developer environments.
> fix(3iD): fix for developer deployments

- src/main/com/kubelt/lib/rpc.cljs
- src/main/com/kubelt/sdk/v1/oort.cljs
- three-id/README.md
- three-id/src/hooks/account.ts
- three-id/src/hooks/sdkAuth.ts
- three-id/src/provider/kubelt.ts
- three-id/src/provider/web3.ts
- three-id/src/screens/AuthLayout.tsx
- three-id/src/screens/funnel/Auth.tsx
- three-id/src/screens/funnel/Gate.tsx
- three-id/src/screens/funnel/Landing.tsx
- three-id/src/screens/profile/Settings.tsx
This PR adds claims checking functionality to the 3iD funnel so that users that can access 3iD will be redirected to their profile settings page if `3iD.enter` claim exists.
Closes #574 
> FEAT(Three-id): Check claims after succesful authentication

- .github/workflows/release.yaml
Adds `CLOUDFLARE_ZONE_ID` environment variables to `release` workflow.
> chore(3iD): add missing environment to release workflow jobs

- three-id/bb.edn
Fixes the cache purging logic to remove all cache entries (by URL) that correspond to all currently deployed files in a given environment.
> fix(3iD): improve purging of deployed URLs

- three-id/src/screens/AuthLayout.tsx
- three-id/tests/e2e/specs/gate-allowed-spec.js
Agreeing to a Signature Request with a wallet that has claims for 3iD allows it to pass the gate.
Investigated flaky behaviour for `sign` which pops up the extension but does it AFTER synpress triggers the click on signature request.
Issue: https://github.com/kubelt/kubelt/issues/602
> chore(three-id): Add claims test which confirms when a wallet is allowed, it can pass gate

- three-id/bb.edn
The intent here was to run smoke tests against both internal and external URLs for a given deployment environment. Unfortunately, it seems as though DDoS protection (or a similar capability) kicks in and causes 403 for all URLs after the host name changes from internal to external, or vice versa.
This leaves the changes in place for future refinement, but only execute smoke tests against the *external* URLs for the deployment environment.
> chore: smoke testing of internal and external URLs

- package-lock.json
- package.json
- src/main/com/kubelt/sdk.cljs
Due to a recent change for the dependency `expo-cli`, there is a version mismatch for `webpack`. This version mismatch causes our builds to fail when trying to run `bb compile:app ...`.
https://github.com/storybookjs/storybook/issues/13332
https://stackoverflow.com/questions/65839447/cannot-read-property-createsnapshot-of-undefined
> chore(3iD): Fix webpack version mismatch due to expo-cli

- 3iD/src/provider/kubelt.ts
- src/main/com/kubelt/lib/rpc.cljs
- src/main/com/kubelt/sdk.cljs
- src/main/com/kubelt/sdk/v1/oort.cljs
These changes [ease](https://github.com/kubelt/kubelt/pull/616/files#diff-ae67f4f0237d224aaa55cf3dad4700e1659726971f332b2173cb80c14599d1db) the rpc calls from js env, avoiding to explicitly
obtain the sdk-rpc-api to allow sdk-rpc calls
Refactoring
Existent tests should add coverage
> chore(sdk-api): Refactor sdk oort rpc api

- .github/workflows/develop.yaml
- 3iD/src/screens/funnel/Gate.tsx
- 3iD/tests/e2e/specs/gate-denied-spec.js
Tests the following flow:
- denied wallet signs
- should get a message to `Try Different Wallet`
- then the account is switched to use an allowed wallet
- allowed wallet signs
- gets accepted into the application
Due to the nature of sessions being saved and a redirect in place from the base route (`/`) to (`/authentication`), it is necessary to disconnect the account from the app for the tests to succeed.
Closes #602
> chore(3iD): Add tests for deny flow with multiple ETH accounts on Metamask

- src/main/com/kubelt/sdk/v1/oort.cljs
- src/test/com/kubelt/rpc/sdk_test.cljs
By default we csk/->kebab-case-keyword on  https://github.com/kubelt/kubelt/blob/fix-rpc-call-response-format/src/main/com/kubelt/lib/json.cljc#L27
Closes #630
> Return camelCase on sdk.oort.callRpc calls

- 3iD/.env.example
- 3iD/tests/e2e/specs/gate-allowed-spec.js
- 3iD/tests/e2e/specs/gate-denied-spec.js
Added a new configuration in the .ENV which should allow us to use multiple wallets throughout testing (for example we might need it in the case of invitations where we want to always maintain an account with an invitation that can check the gating to the invitation screen).
Things to note:
- Cypress automagically injects as an environment variable in the testing any env variable that starts with CYPRESS_ or cypress_. We latch onto this mechanism to inject multiple wallet configurations;
- Cypress automagically does wallet setup before tests, so we need to disable that and do it manually;
- If there is a SECRET_WORDS env variables, that will override whatever values sent to setupMetamask, so that needs to be away.
> CHORE(3iD-testing): Allow multi-wallet

- 3iD/tests/e2e/specs/gate-allowed-spec.js
- 3iD/tests/e2e/specs/gate-denied-spec.js
Tests are failing due to initial assumption that after authentication would come either `/gate` or `/settings` which is no longer the case. It can be a mix of three screens (invite / mint / naming) which has an arrangement that is hard to justify at this point.
> FIX(3iD): Update tests

- 3iD/src/provider/kubelt.ts
`getSDK` is now available throughout the client-side code, as such we can't link SDK restoration to it being null. Solution is to force restoration in case of specific `authenticate` call and ignore it if it doesn't return logged in. This should preserve current behavior.
Manually
> FIX(3iD): Try restore SDK

- 3iD/src/provider/kubelt.ts
- src/main/com/kubelt/sdk/v1.cljs
- src/test/com/kubelt/rpc/nfts_test.cljs
We have had an issue where calls to the SDK `isLoggedIn()` function would always return false. This was caused by:
1. a schema conformance check on the "restored" SDK
2. the schema non-conformance error being returned as an opaque edn map
3. not checking for a valid SDK instance in the calling context
This is a patch that removes the conformance check, so that the SDK is always returned, with no possibility of a schema error. We also add:
Additional work to come:
- restore the schema conformance check after the schema is updated to reflect recent changes; the check should only fail when the restored SDK instance is actually invalid
- improvements to the login status checking
> fix(sdk): update check for login status based on JWT presence

- 3iD/src/provider/kubelt.ts
- 3iD/src/provider/web3.ts
A rather hacky chain changed event implementation. Makes me think investing in some time for the react hooks is really necessary. ATM it forces both accountClearing, SDK purging & window refresh... 
Manually, and with great pain.
> FEAT(3iD): Handle chain changed event

- nftar/index.js
Fix for the `ALCHEMY_KEY` naming issue from this morning.
local/goerli/mainnet
> fix(nftar): Add proper Alchemy API KEY envvar name.

- nftar/.gitignore
- nftar/bin/local_smoke.sh
- nftar/index.js
- nftar/src/app.js
- nftar/src/utils.js
- nftar/tests/utils.test.js
This was blocked by the `jayson` + DO issue on Friday, which is now resolved. Catches up with what's in the Goerli NFTar service:
- Adds the invite contract environment variable and PFP contract environment variables to NFTar so that we can work with both kinds of NFT.
- Changes how we look for NFT ownership so it's more efficient and eliminates a utility function. Better use of the Alchemy API.
- Adds API key, DEV key, and 409 test to `genInvite`.
- Cleans up invite method metadata to match actual.
- Adds `recipient` param to `genInvite`.
- Adds basic debug and performance logging to `genInvite` (and removes some old logging).
- Sets up deprecating `3iD_genInvite` in favour of `3id_genInvite` (ie lowering the 'd').
- Updates date formatting so we don't have to trust client locales.
- …
> feat(nftar): Add Multiple Contract Types, Add Deprecations, Fix Dates

- threeid/app/routes/account.tsx
- threeid/app/routes/account/index.tsx
- threeid/app/routes/auth/nonce/$address.tsx
- threeid/app/routes/onboard/mint/index.tsx
- threeid/app/routes/onboard/mint/load-voucher.tsx
- threeid/app/routes/onboard/name.tsx
As part of recent changes to Oort, we're moving away towards an object package for storing user data. As such, the current `kb_(get/set)Data` endpoints should be transformed to the new package, matching the instructions from https://github.com/kubelt/kubelt-oort/pull/243#issuecomment-1273308343
Not at all
> FIX(3iD): Use oort object package

- .github/workflows/main-icons.yaml
- .github/workflows/next-icons.yaml
- .github/workflows/release-icons.yaml
- platform/icons/.dev.vars.example
- platform/icons/bin/get_signed_url.sh
- platform/icons/src/index.ts
- platform/icons/wrangler.toml
- yarn.lock
- previous service configuration did not make it publicly routable
> fix(icons): update workflows and auth provisioning

- projects/nftar/index.js
- projects/nftar/package.json
- projects/nftar/src/app.js
Add a generator that takes two input URLs, sees if the result is cached, then if needed combines them using an SVG template, uploads them to the Cloudflare Image service, and returns the URL.
Local.
> feat(nftar): Add OG:Image Generator

- platform/starbase/lib/openrpc/package.json
- platform/starbase/worker/package.json
- yarn.lock
Replaces local `file://` package dependency specification with yarn workspaces resolution across monorepo packages with the hope that this unbreaks the build.
> fix(sb): use yarn workspace resolution over file:// deps

- apps/threeid/app/routes/$profile.tsx
- Closes #964 
- Alchemy NFT querying doesn't work on Goerli with ENS name
- Throws exception on testnet when trying to get NFTs for ENS name
Manually, on local
> bug(threeid): ens profile ownership check

- apps/threeid/app/assets/missing-nft.svg
- apps/threeid/app/components/nft-collection/ModaledNft.tsx
- apps/threeid/app/components/nft-collection/SelectableNft.tsx
Added an `onError` handler to NFT renderers which replace failed NFT loads with a placeholder graphic.
- Closes #965 
Visually, locally
> bug(threeid): nft load fail placeholder

- .github/workflows/main-starbase.yaml
- .github/workflows/next-starbase.yaml
- .github/workflows/release-starbase.yaml
- apps/console/wrangler.toml
- platform/starbase/wrangler.toml
Adds GHA workflows for starbase.
- `main-starbase`
- `next-starbase`
- `release-starbase`
- sets up service binding for `console-{dev,next,current}` to `starbase-{dev,next,current}`
I did some experimentation with dependency caching; the `actions/cache@v3` action doesn't appear to care about the default `working-directory` setting, relative paths in the `path:` configuration and `hashFiles()` argument result in an error message.
> chore(sb): workflows

- apps/threeid/app/components/modal/Modal.tsx
- apps/threeid/app/components/nft-collection/ModaledNft.tsx
- apps/threeid/app/components/nft-collection/NftModal.tsx
Small tweaks to the modal component to support larger screen real estate. Should hold more information per line now while not being too different.
Visually, by comparison to Figma
> fix(threeid): expand modal real estate

- apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx
To simulate a skeleton loader as part of the infinite scroll, had to resort to a hack that simulates the Masonry layout without being an actual masonry. I think this should be enough for now until we do a heavier rework of the public profile gallery page.
Locally with 5 breakpoints.
> feat(threeid): profile skeleton loader

- projects/nftar/Dockerfile
GIFs, WEBP, PNG, SVGs, and JPGs now all render correctly as og:images. Dockerfile changed to run Chromium using Puppeteer locally, and in Cloud Run, as an image renderer.
Local and Goerli service.
> feat(nftar): Fix OG:Image Rendering

- apps/threeid/app/components/nft-collection/NftModal.tsx
Added an animated-pulsing 24remx24rem skeleton for nft modals.
Visually
> feat(threeid): nft modal skeleton

- package.json
- platform/starbase/package.json
- platform/starbase/src/index.ts
- platform/starbase/wrangler.toml
- yarn.lock
Use `@kubelt/platform.commons` utility `isAuthenticated()` from starbase worker to authenticate requests.
Incidental:
- remove a couple of legacy dependencies from root `package.json`:
- `classnames`: not used with tailwind
- `wagmi`: should be required by specific workspaces that require it
> feat(sb): bind to passport service to authenticate calls

- packages/cores/user/index.ts
- packages/cores/user/schema.ts
- platform/starbase/curl/kb_appList.json
- platform/starbase/package.json
- platform/starbase/src/index.ts
- platform/starbase/wrangler.toml
> feat(sb): store and retrieve application IDs for users

- apps/threeid/tailwind.config.js
Added a builder to generate relative paths for imported modules. This is in response to production graphical issues when changing deployment strategies.
Locally
> fix(threeid): tailwind config relative modules

- packages/cores/application/index.ts
- packages/cores/application/schema.ts
- packages/cores/user/index.ts
- packages/cores/user/schema.ts
- packages/openrpc/component/index.ts
- packages/openrpc/constants.ts
- packages/openrpc/impl/client.ts
- packages/openrpc/impl/index.ts
- packages/openrpc/impl/router.ts
- packages/openrpc/index.ts
- platform/starbase/curl/kb_appAuthCheck.json
- platform/starbase/curl/kb_appAuthInfo.json
- platform/starbase/curl/kb_appProfile.json
- platform/starbase/curl/kb_appStore.json
- platform/starbase/package.json
- platform/starbase/src/index.ts
- platform/starbase/src/schema.ts
- platform/starbase/src/token.ts
- yarn.lock
- when creating an `openrpc.method()` an `auth` fn can be supplied
- this is effectively a middleware that is executed for that specific RPC method invocation
- if it returns `void`, the auth check has succeeded
- if it returns a `Response`, the request handling is short-circuited and the response is returned
- `kb_initPlatform`
- `kb_appProfile`
-  `kb_appAuthCheck`
- `kb_appRotateSecret`
- `kb_appPublish`
- `kb_appAuthCheck` (replaces `kb_appAuthInfo`)
> feat(sb): misc improvements

- .yarnrc.yml
After installing the yarn plugin `interactive-tools` and running the included `upgrade-interactive` tools, the following changes (less the comments) were made to the `.yarnrc.yml` file. Sharing here in case they make sense to keep.
```
$ npx yarn plugin import interactive-tools
$ npx yarn upgrade-interactive
```
> chore: save changes to .yarnrc.yml after using upgrade-interactive

- projects/nftar/src/app.js
- projects/nftar/src/utils.js
- projects/nftar/tests/datauri.js
- projects/nftar/tests/utils.test.js
Fixes broken OpenGraph tags for people with Cryptopunks PFPs.
For some unclear reason (user agent?) the Cryptopunks app responds with a `403` when called from GCP with the legacy `Request` API. Fix is to use the contemporary `fetch` API to get the byte stream of the image and then convert _that_ to a data URI.
Local and Goerli
> fix(nftar): Fix Cryptopunks 403 Error

- .gitignore
Update `.gitignore` to ignore subsidiary `.yarn` directories, e.g. `platform/.yarn`, `app/.yarn`, etc.
> chore: ignore nested .yarn directories

- platform/address/src/env.ts
- platform/address/src/index.ts
- platform/commons/src/utils/checkEnv.ts
- platform/galaxy/package.json
- platform/galaxy/src/env.ts
- platform/galaxy/src/index.ts
- platform/icons/package.json
- platform/icons/src/env.ts
- platform/icons/src/index.ts
- platform/starbase/src/env.ts
- platform/starbase/src/index.ts
- yarn.lock
It is not possible to have a startup time check as the environment object is only present in the fetch context only. The best possibility is to declare required environment keys in a single place and have them looked up like middleware in the `fetch` handler. I think it'd be perhaps better to guard references to the environment keys instead of doing it like this.
> chore(platform): check environment

- apps/threeid/app/components/inputs/InputText.tsx
- apps/threeid/app/components/inputs/InputTextarea.tsx
Tailwind doesn't know how to handle computed classes like 'p' + 'l' + '-3' `pl-3` so we must be specific about them. Inputs will be refactored and moved to design system in the future and proper twcss will be used.
Visually
> fix(threeid): computed tailwind classes

- packages/openrpc/component/alarm.ts
- packages/openrpc/component/index.ts
- packages/openrpc/impl/client.ts
- packages/openrpc/impl/context.ts
- packages/openrpc/impl/index.ts
- packages/openrpc/impl/utility.ts
- packages/urns/application.ts
- platform/edges/src/index.ts
- platform/starbase/curl/kb_appCreate.json
- platform/starbase/curl/kb_appList.json
- platform/starbase/curl/kb_appRotateSecret.json
- platform/starbase/package.json
- platform/starbase/src/edge.ts
- platform/starbase/src/index.ts
- platform/starbase/src/nodes/application/index.ts
- platform/starbase/src/nodes/application/schema.ts
- platform/starbase/src/schema.ts
- platform/starbase/src/token.ts
- yarn.lock
- you must now call `kb_appRotateSecret` to generate the OAuth client secret
- this is used in subsequent calls as the app identifier
- returns the plaintext secret _once_ in response to this call
- secret is stored hashed, and never handled as plaintext in the system again
- this field stores the current hashed application secret
- secret rotation is _destructive_, overwriting the stored secret
- used to name a starbase application node
- utility for working with application URNs (membership testing, construction)
> feat(sb): more edges integration, flesh out API methods

- .github/workflows/main-access.yaml
- .github/workflows/main-account.yaml
- .github/workflows/main-galaxy.yaml
- .github/workflows/next-access.yaml
- .github/workflows/next-account.yaml
- .github/workflows/next-galaxy.yaml
- .github/workflows/release-access.yaml
- .github/workflows/release-account.yaml
- .github/workflows/release-galaxy.yaml
Further cleanup of env var references and GHA secrets for Account, Access and Galaxy pipelines.
Contributes to closure of #1121.
- Chore
It hasn't. Pipeline would have to execute to test.
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] My changes generate no new warnings
> chore(gha): env var/secrets cleanup for Access, Account and Galaxy

- platform/starbase/curl/kb_appPublish.json
- platform/starbase/curl/kb_appRotateSecret.json
- platform/starbase/curl/kb_appUpdate.json
- platform/starbase/src/error.ts
- platform/starbase/src/index.ts
- platform/starbase/src/nodes/application/index.ts
- platform/starbase/src/nodes/application/schema.ts
- platform/starbase/src/schema.ts
Allow applications to be "published" using the `kb_appPublish` RPC method of `@kubelt/platform.starbase` service.
- this is only used for the case where loading fixture data, and should be removed once fixture objects are no longer necessary
- the app secret must be set
- the app name must be set
> feat(sb): all applications to be published

- .github/workflows/next-address.yaml
Fixes typo in secrets reference for the NFTar key for the "next" workflow.
Has not. Pipeline run will test.
> fix(gha): Fixing typo in secrets reference in GHA workflow for Address - next.

- packages/graph/impl/index.ts
- packages/graph/index.ts
- packages/graph/types.ts
- platform/edges/curl/kb_makeEdge.json
- platform/edges/src/db/impl/index.ts
- platform/edges/src/db/impl/insert.ts
- platform/edges/src/db/impl/remove.ts
- platform/edges/src/db/impl/select.ts
- platform/edges/src/db/index.ts
- platform/edges/src/db/types.ts
- platform/edges/src/error.ts
- platform/edges/src/index.ts
- platform/edges/test/db/basic.ts
- platform/starbase/src/index.ts
- this was previously done in "expedient fashion" by returning a bulk list of edges and filtering in-app
- this logic is pushed into the `edges` service and the filtering performed using SQL
- an edge using to look something like `{ "tag": "...", "srcUrn": "...", "dstUrn": "..."}`
- the new shape is something like: `{ "tag": "...", "src": { urn, id, qc, rc, ...} }`
- we don't yet store permissions when creating edges, for now this will always be empty list
> feat(edges): update shape of returned edges, include more data

- apps/package.json
- package.json
- platform/package.json
Removed limitation that yarn applies by default for parallel invocations, so that we're able to run all workers/apps locally, using a single command (yarn dev for workers, yarn start for apps)
Ran the commands locally in appropriate folders.
> chore(dx): Removed yarn limit on parallel invocations.

- .github/workflows/main-edges.yaml
- README.md
The following error is occurring the in the `main-edges` workflow when invoking `wrangler d1` commands using the [cloudflare/wrangler-action](https://github.com/cloudflare/wrangler-action):
```
[ERROR] A request to the Cloudflare API (/accounts/***/d1/database/7e2bb4f6-9a3e-4136-aa71-d634db545b4d/query) failed.
Authentication error [code: 10000]
```
Things tried:
> fix(gha): fix wrangler auth error in edges workflow

- packages/openrpc/middleware/local.ts
- packages/platform-clients/starbase.ts
- packages/utils/index.ts
- packages/utils/isFromCFBinding.ts
- platform/galaxy/src/env.ts
- platform/galaxy/src/schema/resolvers/address.ts
- platform/galaxy/src/schema/resolvers/nfts.ts
- platform/galaxy/src/schema/resolvers/profile.ts
- platform/galaxy/src/schema/resolvers/utils/index.ts
- platform/galaxy/wrangler.toml
- platform/starbase/src/constants.ts
- platform/starbase/src/index.ts
- platform/starbase/src/nodes/application/apiKeyUtils.ts
- platform/starbase/src/nodes/application/index.ts
- platform/starbase/src/nodes/application/schema.ts
- platform/starbase/src/schema.ts
- platform/starbase/src/types.ts
Adds API key validation functionality to starbase and implements a API key check in Galaxy only for non-bound service requests.
Contributes to closure of #1190 
```
// Starbase
curl -X POST \
-H 'Content-Type: application/json' \
localhost:9090/jsonrpc \
-d '{ "jsonrpc": "2.0", "method": "kb_appApiKeyCheck", "params": [{ "apiKey": "(API key)"}] }'
// Galaxy
curl -X POST \
-H 'Content-Type: application/json' \
-H 'x-galaxy-key: (API key)' \
localhost:8787 \
-d '{ "query": "{ profileFromAddress(addressURN: \"(some address URN)\"){ displayName }}" }'
```
> feat(galaxy|starbase): API key validation

- apps/console/app/routes/apps/$clientId/index.tsx
- apps/console/app/utilities/platform.server.tsx
- packages/platform-clients/starbase.ts
- platform/starbase/src/index.ts
- platform/starbase/src/nodes/application/index.ts
- platform/starbase/src/nodes/application/schema.ts
- platform/starbase/src/schema.ts
- platform/starbase/src/types.ts
Implements user-facing feature of being able to roll the API key. Also includes refactorings to remove need for worker method to clear the secrets to make it work in Remix.
- Closes #1190 
> feat(console): API key rolling implementation

- apps/profile/app/components/nft-collection/ProfileNftCollection.tsx
- apps/profile/app/helpers/nfts.ts
- apps/profile/app/routes/nfts/collection.tsx
- apps/profile/app/routes/nfts/index.tsx
Sorting NFTs now is done on server. Sorting filters is completely relying on that so that fixes the issue.
Plus adding greedy merge of two sorted NFT which increases speed.
- Closes #1233
Locally
> fix(threeid): sort nfts on server

- apps/console/app/components/SiteMenu/index.tsx
Application submenu once an app is selected in Console wasn't showing on mobile. This fixes it.
Visually
> fix(console): Fixes submenu display on mobile.

- apps/console/app/components/Applications/Auth/ApplicationAuth.stories.tsx
- apps/console/app/components/Applications/Auth/ApplicationAuth.tsx
- apps/console/app/components/Applications/Dashboard/ApplicationDashboard.tsx
- apps/console/package.json
- packages/design-system/src/atoms/copier/Copier.tsx
- packages/design-system/src/atoms/form/ReadOnlyInput.tsx
- yarn.lock
When secrets are revealed (upon new app creation or on secret rotation) a copy button is displayed over the secret field to copy the secret to the clipboard. A toast message noting the copy operation is added also.
- Closes #1345 
- New app
- Rotate API key in Dashboard page
- Rotate Client secret in Dashboard page
- Rotate Client secret in OxAuth page
> feat(console): Display button to copy secrets on reveal 

- apps/passport/app/routes/authenticate/$address/sign.tsx
- apps/passport/app/routes/authenticate/$address/token.tsx
- apps/passport/app/routes/authenticate/github/callback.ts
- apps/passport/app/routes/authenticate/google/callback.ts
- apps/passport/app/routes/authenticate/microsoft/callback.ts
- apps/passport/app/routes/authenticate/twitter/callback.ts
- apps/passport/app/routes/authorize/index.tsx
- apps/passport/app/utils/cacheImageToCF.server.ts
- apps/profile/app/routes/$type.$address.tsx
- apps/profile/app/routes/account/gallery.tsx
- packages/urns/access.ts
- packages/urns/account.ts
- packages/urns/address.ts
- packages/urns/application.ts
- packages/urns/idref.ts
- packages/urns/index.ts
- packages/urns/package.json
- platform/address/src/jsonrpc/methods/initVault.ts
- platform/address/src/jsonrpc/methods/resolveAccount.ts
- platform/address/src/jsonrpc/middlewares/checkCryptoNode.ts
- platform/address/src/jsonrpc/middlewares/parse3RN.ts
- platform/starbase/src/jsonrpc/methods/rotateApiKey.ts
- yarn.lock
Added:
Closes #1413 
- Chore 
Locally across eth and OAuth accounts.
> chore(platform): Typed URN and IDRef utils

- apps/console/app/components/Applications/Dashboard/ApplicationDashboard.tsx
- packages/design-system/src/atoms/form/MultiSelect.tsx
Fixes storybook deplopy and disables multi-select on drop-down
- Closes #1518 
> fix(console): storybook and no dropdown

- apps/console/app/routes/apps/$clientId/auth.tsx
- apps/console/app/utilities/session.server.tsx
- apps/passport/app/auth.server.ts
- apps/passport/app/components/authentication/Authentication.tsx
- apps/passport/app/components/authorization/Authorization.tsx
- apps/passport/app/root.tsx
- apps/passport/app/routes/authenticate/index.tsx
- apps/passport/app/routes/authorize/index.tsx
- platform/starbase/src/jsonrpc/methods/getAppPublicProps.ts
- platform/starbase/src/jsonrpc/router.ts
Cleans up authorization screen, param checks, app name, etc.
- Closes #1498
- By temporarily enabling setting of scopes in Console, setting some scopes on a couple of apps, and then hitting the `/authenticate` endpoint in passport with `client_id` and other query params.
> fix(passport): Authn & Authz screen icon, name and cleanup

- apps/console/app/routes/apps/$clientId.tsx
- apps/console/app/routes/dashboard/index.tsx
- apps/passport/app/routes/authorize.tsx
- apps/profile/app/helpers/nfts.ts
- apps/profile/app/helpers/profile.ts
- apps/profile/app/root.tsx
- apps/profile/app/routes/$type.$address.tsx
- apps/profile/app/routes/account/gallery.tsx
- apps/profile/app/routes/account/settings/connections/rename.tsx
- apps/profile/app/routes/account/settings/links.tsx
- apps/profile/app/routes/account/settings/profile.tsx
- apps/profile/app/routes/account/settings/profile/update-cover.tsx
- apps/profile/app/routes/nfts/collection.tsx
- apps/profile/app/routes/nfts/index.tsx
- apps/profile/app/utils/session.server.tsx
- packages/utils/getAuthzHeaderConditionallyFromToken.ts
- packages/utils/getAuthzTokenFromReq.ts
- packages/utils/index.ts
- platform/galaxy/src/schema/resolvers/utils/index.ts
Changed the header for Galaxy calls (client and resolver middleware) to the `Authorization: Bearer (token)` format. 
Done this through introduction of 2 package utilities:
- One to produce appropriate headers or empty object from token
- One to get token from headers or returned undefined, in case of no Authorization header. This is used for operations with public access.
This brings user docs and code in alignment.
- Closes #1555
- Chore
- Logged in to Console and Profile with multiple accounts (MS, github, wallet) and verified avatar, name, other profile props, links and connected accounts.
- Viewed public profiles for accounts above without being logged in.
> chore(galaxy): Changed header to standard "Authorization: Bearer (token)" format.

- platform/images/src/jsonrpc/methods/getOgImage.ts
There is an exception thrown when no cover photo is set and the image worker expects it in order to generate the header OG profile image. This PR supposedly fixes this issue.
- Closes #1581 
1. Remove cover image
2. See that 404 is not thrown anymore, but empty cover is presented
> BUG(Profile): deleting OF image gets me 404 page

- platform/edges/drizzle/20230208183719/migration.sql
- platform/edges/drizzle/20230208183719/snapshot.json
- platform/edges/migrations/0001_adding_creationtimestamp.sql
- platform/edges/src/db/insert.ts
- platform/edges/src/db/schema.ts
- platform/edges/src/db/select.ts
- platform/edges/src/db/types.ts
- platform/edges/src/jsonrpc/validators/edge.ts
Adds `createdTimestamp` column to `edge` table as well as exposes a field by the same name in the edge records returned by edge queries. The value of this field is set to a UTC representation of the edge creation time.
- Closes #1599
- Ensuring date is entered in the local .sqlite DB for new edges, eg. when you create a new app in Console
- Ensuring the value comes through when retrieving that edge, eg. when listing apps.
> feat(edge): Add created timestamp column on edges using drizzle migration

- apps/profile/app/utils/session.server.tsx
The token expiration time is in seconds and `Date.now()` returns time in
milliseconds. The comparison results in expiration always because of that.
- Manual
> fix(profile): compare the expiration time in milliseconds

- apps/passport/package.json
Previous commit included the disabling of the sideEffect flag for Passport, which led to funky fetch handler errors when the first request was recieved by passport. This reverses that change.
Running Passport locally and being able to login through any provider without error.
> fix(passport): Reversing sideEffect flag from previous commit

- packages/urns/access.ts
- platform/access/src/constants.ts
- platform/access/src/jsonrpc/methods/exchangeToken.ts
- platform/access/src/jsonrpc/methods/revokeSession.ts
- platform/account/src/jsonrpc/methods/getSessions.ts
Replaces the previous implementation where the grant type for an access edge was being encoded as an r-comp of the Access node of the edge. This moves it to the edge tag, where a user either authenticates (`EDGE_AUTHENTICATES`) what's represented in an Access node, or authorizes (`EDGE_AUTHORIZES`) what's represented in an Access node.
Log in with a new account, and go to Profile. This should create both an authentication edge (for Passport) and an authorization edge (for Profile) in the DB. Edge table reflects the grant type in the tag column; rcomp table reflects the client_id for the authorization access edge.
> Moving the grant type to be encoded in Access edge tag.

- packages/urns/account.ts
- packages/urns/application.ts
- platform/account/src/jsonrpc/methods/setProfile.ts
- platform/edges/src/db/update.ts
- platform/edges/src/jsonrpc/methods/updateNodeComps.ts
- platform/edges/src/jsonrpc/router.ts
- platform/starbase/src/jsonrpc/methods/createApp.ts
- platform/starbase/src/jsonrpc/methods/updateApp.ts
- platform/starbase/src/jsonrpc/ownAppsMiddleware.ts
Adds q-comps to Account and ApplicationURNs to store their name and image, respectively. This is now updated in the Edges node representing that URN. Mutation calls in Account and Starbase have been enhanced to call the node-updating method in Edges too.
Edges should now be up to date with name&image info. 
- Closes #1631
- Chore
For account, by settings and resetting name. For application, by creating and then updating apps - their names and icons.
> chore(platform): Update app and account URNs with q-params in edges.

- apps/passport/app/routes/authorize/index.tsx
- platform/starbase/src/jsonrpc/methods/checkAppAuth.ts
- platform/starbase/src/jsonrpc/methods/getAppPublicProps.ts
Throws exceptions in cases where an unpublished app is being queried for public props or when a credentials check is happening against it (exchange code and refresh token calls)
- Closes #1626
- Security Fix
- With the Profile app unpublished, attempted to go to Profile from Console.
- With the Profile app unpublished, attempted to display branded login page. 
- Tested with wallet and github login
> fix(platform): Throw on attempts to read public props or verify client creds for unpublished apps.

- apps/passport/app/root.tsx
- apps/passport/app/routes/authenticate.tsx
- packages/design-system/src/pages/error/ErrorPage.tsx
- Closes #1668 
- Security Fix
- Visually in design system
- Functionally by throwing an error on authenticate route
> chore(passport): remove Pepe from error pages

- apps/profile/app/routes/account/settings/links.tsx
The <InputText> used inside the links route is our custom component; the behavior of onChange is already handled and only the changed value gets sent outside the component, not the event that has a target and a value. Thus the error. Now, we get the value directly and populate the state.
- Closes #1666 
Reproducing with dev tools opened, understanding the error, fixing and trying it again with dev tools opened.
> fix(profile): Value JS error in when editing links

- apps/profile/app/routes/nfts/collection.tsx
- platform/galaxy/src/schema/resolvers/nfts.ts
closes #1696
Fixes owner as accountURN to not duplicate urn prefix
Bug fix (non-breaking change which fixes an issue)
> fix(galaxy): double apply urn prefix

- apps/passport/app/root.tsx
- apps/passport/app/session.server.ts
- Added 400 days expiration date for cookie
- If context has new consoleParams that have a different clientId, replaces console props cookie
- Closes #1695 
- Depends on #1692 
1 - Go to Profile App A
2 - Get redirected to Passport
3 - Get Profile App A branding
4 - Wait 6 minutes
5 - Go to Passport app
6 - See Profile App A branding
7 - Go to Profile App A
8 - Log out
9 - Go to Profile App B
10 - Get redirected to Passport
11 - See Profile B branding
> fix(passport): console params session should not expire

- scripts/generate-appleid-client-secret.js
The script can be executed in two forms.
The first form accepts positional options.
```shell
scripts/generate-appleid-secret $TEAM_ID $CLIENT_ID $PRIVATE_KEY_FILE
```
The second is using environment variables.
- TEAM_ID
- CLIENT_ID
- PRIVATE_KEY
> chore(scripts): generate AppleId client secret

- platform/edges/src/db/index.ts
- platform/edges/src/db/select.ts
- platform/edges/src/db/types.ts
- platform/edges/src/jsonrpc/methods/getEdges.ts
- platform/edges/src/jsonrpc/validators/edge.ts
getEdges interface now returns an object containing edges and a metadata object as follows:
```
{ 
edgesReturned: number,
limit?: number,
offset?: number
}
```
- Closes #1744
- Chore
Quick regression pass on functionality that uses edges, through console (authz summary), profile (links and public profile)
> chore(edges): Implements results metadata object

- platform/edges/src/db/select.ts
Fixes ordering issue when limits are applied
- Closes #1775
Tested on top of Emil's PR, by replicating the scenario that led to the issue being reported. In Console, had multiple pages of users and they were ordered in descending order of creation through the whole resultset, and not just the page I was on.
> fix(edges): Fixes ordering issue when limits are applied

- platform/edges/src/db/index.ts
- platform/edges/src/db/select.ts
- platform/edges/src/jsonrpc/methods/findNode.ts
Implements the `findNode` method that takes single node parameters and returns a single node, if found. Returns undefined if not found; throws if more than 1 node was found with given criteria. 
- Closes #1757
- Chore
Temporarily added additional statement to codebase to test the findNode path:
- criteria on `baseUrn` alone
- criteria with the comps alone
- criteria with combination of `baseUrn` and comps
- criteria for which there isn't a node in the DB
> chore(edges): Implemented findNode

- apps/passport/app/routes/connect/$address/sign.tsx
Error gets thrown if accessing passport directly. This fixes that.
Did the flow with error then without.
> fix(passport): handle-empty-app-data-in-sign-flow

- apps/profile/app/utils/cta.client.ts
Added OR condition to profile completion. Had to remove cover because currently we have no way of knowing if covered is uploaded by user or auto-generated. This feels like a larger work than worth feature. Up to reviewer if it's OK to cut out profile or if we start the conversation about how we achieve this.
- Closes #1784 
1. Created new account
2. Profile CTA visible
3. Updated job field
4. Links CTA now visible instead
> bug(profile): complete profile cta still shows after updating one field

- apps/passport/app/components/authentication/Authentication.tsx
Made auth screen take up full mobile view
- Closes #1772 
Desktop:
Galaxy:
Pixel:
iPhone:
> chore(passport): mobile view for auth screen update

- apps/passport/app/components/connect-button/ConnectButton.tsx
Display ensName or address on login button when wallet is connected
- Closes #1773 
- There's a flicker between address & ensName if ensName exists. I didn't find any way to interact with the connect button in a way that would allow me to resolve this flicker;
- Displaying ens avatar feels like a large involvement vs. gains for now as the connect button component is very unfriendly with modifying state both inside and outside it.
> chore(passport): connect button show who is connected

- apps/profile/app/utils/session.server.tsx
The user session data was overwritten completely after the refresh token is
exchanged. The refresh token is now permanent so it is not present in the
exchange result. This patch updates the access token stored in the session data
directly.
- Fixes #1824
- Manual
> fix(profile): update access token in the user session data directly

- apps/profile/app/utils/session.server.tsx
Terminates the user session and redirects to the passport for login if the
refresh token is missing in the user session data.
- Manual
> feat(profile): redirect to `/signout` if refresh token is missing

- apps/profile/app/routes/account/connections/rename.tsx
Re-added `await` to method call returning Promise
- Closes #1873 
This is the test, as well as the fix.
> bug(profile): rename accounts

- apps/passport/app/routes/connect/email/otp.ts
- apps/profile/app/helpers/profile.ts
- apps/profile/app/routes/account/connections/index.tsx
- packages/galaxy-client/gql/address.graphql
- packages/galaxy-client/index.ts
- packages/platform-middleware/trace.ts
- packages/types/address.ts
- packages/utils/generateRandomString.ts
- platform/address/src/constants.ts
- platform/address/src/context.ts
- platform/address/src/jsonrpc/methods/generateEmailOTP.ts
- platform/address/src/jsonrpc/methods/getAddressProfile.ts
- platform/address/src/jsonrpc/methods/resolveAccount.ts
- platform/address/src/jsonrpc/methods/verifyEmailOTP.ts
- platform/address/src/jsonrpc/middlewares/checkOAuthNode.ts
- platform/address/src/jsonrpc/router.ts
- platform/address/src/jsonrpc/validators/profile.ts
- platform/address/src/nodes/address.ts
- platform/address/src/nodes/email.ts
- platform/address/src/types.ts
- platform/address/src/utils.ts
- platform/address/wrangler.toml
- platform/email/src/jsonrpc/router.ts
- platform/email/wrangler.toml
- platform/galaxy/src/schema/resolvers/address.ts
- platform/galaxy/src/schema/types/address.ts
Implements Email OTP generation and verification, along with association with account (new or existing if JWT is provided). 
- Closes #1898
New accounts: 
1. `curl -H 'Content-Type: application/json' http://localhost:10401 -H 'Authorization: Bearer (jwt)' -d '{"query": "{ connectedAddresses { baseUrn, qc } } "}' `
2. `curl 'localhost:10001/connect/email/otp?address=blah2@blah.com'`
3. `curl 'localhost:10001/connect/email/otp' -X POST -H "Content-Type: application/x-www-form-urlencoded"  -d "address=blah2@blah.com&state=(state value from previous step)&code=(code from email in console)"`
4. Rerun step 1
For connecting to existing accounts
1. Log in to Passport and take note of the Passport cookie value.  
2. Repeat steps above …
> feat(platform): Email OTP verification

- apps/passport/app/routes/authenticate/$clientId.tsx
- apps/passport/app/routes/connect/apple/callback.ts
- apps/passport/app/utils/authenticate.server.ts
- apps/profile/app/routes/account/connections/index.tsx
- platform/access/src/jsonrpc/validators/IdTokenProfileSchema.ts
- platform/access/src/utils/getIdTokenProfileFromAccount.ts
- platform/address/src/jsonrpc/validators/oauth.ts
- platform/address/src/jsonrpc/validators/profile.ts
The profile data does not include `name` if the user has been authenticated
before.
The id token generation in the access worker requires a `pfp` set.
- Closes #1883
> fix(passport): provision appleid profile

- apps/passport/app/routes/connect/$address/sign.tsx
- apps/passport/app/routes/connect/$address/token.tsx
- platform/address/src/jsonrpc/methods/verifyNonce.ts
- platform/address/wrangler.toml
Removes unnecessary `authorize()` call in address worker and allows us to remove the Access service binding from it. Only affected wallet logins.
- Chore 
- Validated login with wallet
- Validated connected account with wallet
- Validated being unable to connect already connected wallet
- Validated error being produced in case of invalid nonce.
> chore(address): Remove unnecessary authorization call and Access service bindings.

- apps/console/app/routes/apps/$clientId/auth.tsx
- apps/passport/app/routes/authorize/index.tsx
- packages/design-system/src/atoms/form/MultiSelect.tsx
- packages/errors/index.ts
- packages/platform-clients/address.ts
- packages/security/persona.ts
- packages/security/scopes.ts
- packages/types/application.ts
- platform/access/src/errors.ts
- platform/access/src/jsonrpc/methods/authorize.ts
- platform/access/src/jsonrpc/methods/exchangeToken.ts
- platform/access/src/jsonrpc/methods/getPersonaData.ts
- platform/access/src/jsonrpc/router.ts
- platform/access/src/nodes/access.ts
- platform/access/src/nodes/authorization.ts
- platform/edges/src/db/select.ts
- platform/starbase/src/jsonrpc/validators/app.ts
Implements the necessary bits to support functionality for OIDC scopes `email` and `profile`, including accepting the selection of a email-based connected account URN to populate the email claim value in the ID token.
Console now supports settings default scopes in the OAuth page. 
Note: currently only works for authorizations for apps owned by currently logged in user. See #2011
- Closes #1976
Context:
- App created in Console with `email`, `profile` and `openid` scopes.
- Connected an email-based account to my account and noted its addressUrn.
- Hardcoded the addressUrn in `authorize/index.tsx` in the ActionFunction to send it's value in the `personaData` param of the `formData`.
1. Send request to `/authorize` with client ID …
> feat(platform): OIDC basic scope support (`email`, `profile`).

- apps/passport/app/utils/profile.ts
[galaxy-client](https://github.com/proofzero/rollupid/blob/b591f8f65de7db56bbc3254b0a3e47bf0140b7b8/packages/galaxy-client/gql/address.graphql#L49) applies a field alias: `id` => `discordId` which was implemented to
overcome type difference on the `id` field in Discord type. This alias
doesn't apply in the profile data original source which the passport
application gets.
- Manual
> fix(passport): discord user icon

- apps/passport/app/routes/authorize/index.tsx
- apps/passport/app/routes/connect/email/otp.ts
- apps/passport/app/routes/token.tsx
- apps/passport/app/utils/authenticate.server.ts
- packages/utils/errors.ts
Tweak JSON error wrapper to allow using explicit `throw` statements. This helps the type system indentify throw statements as execution control statements
Made multiple `/authorize` calls with wrong parameters to trigger different errors that get thrown with the new `JsonError()` wrapper
> fix(platform): Tweak JSON error wrapper to allow using explicit `throw` statements

- apps/passport/app/session.server.ts
- apps/passport/app/utils/authenticate.server.ts
Addresses issues with encoding of scope values externally (space delimited) vs internally (string array).
- Closes #2044
- Login to Passport Settings and log out
- Craft authorization request with multiple scope values. Should present with login screen (authenticate with OAuth to take you away from current origin). Once you're redirected back, the authz with the right scopes should be presented.
> fix(passport): Fix encoding of scope values when switching from internal to external representation.

- apps/passport/app/routes/authenticate/$clientId/index.tsx
Addresses the transition into the authz screen when going with the "Continue with" option in the login screen.
- Log in to passport
- Delete console_param_last cookie
- Craft authz request
- When presented with login screen, choose Continue with.
- Should land on authz screen with params as crafted above.
> fix(passport): Addresses "Continue with" scenario.

- apps/passport/app/routes/authorize/index.tsx
When hitting Cancel on the authz screen, the console param cookies get deleted before the redirect.
- Closes #2046
- Craft request to get the authz screen. Copy the URL
- Hit cancel. You should be redirected to the redirect_uri with some query params
- Paste the URL from step 1 and try again, you should be presented with a login screen before getting to authz screen.
> fix(passport): Clear console param cookies on authz screen cancellation

- apps/passport/app/routes/authorize.tsx
- apps/passport/app/session.server.ts
- apps/passport/app/utils/authenticate.server.ts
- apps/passport/app/utils/authorize.server.ts
- packages/design-system/src/atoms/email/EmailSelect.tsx
- Adds checks to authenticate each authorization, to avoid scenarios where authorizations part-way through authentication would be superceded by other authorization requests. 
- Tweaks email dropdown placeholder to match Figma.
- Adds check to allow passthrough to Passport Settings after logging in to it. Now Passport Settings has the same session behavious as Console.
Closes #2059
- Log in to Passport Settings. Go to Passport root URL. Should pass you through to Passport settings.
- Initiate a authorization request (craft manually). Should prompt you for account to log in with, then present authz screen.
- In Passport Settings, initiate a connect account flow but don't complete it. Part way …
> fix(passport): Adds checks to authenticate each unique authorization.

- apps/passport/app/utils/authenticate.server.ts
- apps/passport/app/utils/authorize.server.ts
Fixes the way the redirect URI is compared between the authz query params and authz param cookie to exclude redirect URI query params. This was causing issue when an additional param of `error` was being added in the scenario when a connected account flow was attempted with an already connected account.
- Closes #2078
Log on to Passport settings and initiate a Connect account flow. Choose an account that's already connected elsewhere. You should be redirected to the Account screen and see the toast message with the error.
> fix(passport): redirectURI matching without queryparams

- apps/passport/app/routes/authorize.tsx
- platform/starbase/src/jsonrpc/methods/getAppPublicProps.ts
- platform/starbase/src/jsonrpc/validators/app.ts
Checks redirectURI on authorize screen with the one configured in console.
- Closes #2060
1. went to authorize screen with invalid redirect URL (different from the one that was set in console)
2. got an error
3. changed it so redirect URI in link matches with one in console
4. worked
5. went back to invalid redirect URI, updated it in console configurations so they match
6. reloaded page -> and it worked
> fix(passport): redirect uri validation

- apps/passport/app/routes/authenticate/$clientId/index.tsx
- apps/passport/app/routes/authorize.tsx
- apps/passport/wrangler.toml
- packages/design-system/src/atoms/email/EmailSelect.tsx
- packages/design-system/src/molecules/email-connection-modal/EmailConnection.tsx
- packages/security/persona.ts
- packages/utils/getNormalisedConnectedEmails.ts
Adds apple as an email provider in the email dropdown component
- Closes #2087
1. Setted up ngrok server that was forwarding to my passport local (to be able to login with apple)
2. Created new account with apple provider
3. went to `http://{ngrok-url}//authorize?client_id={client_id}&redirect_uri=http://localhost:10003&state=foo&scope=profile+email/`
4. This is the following: 
https://user-images.githubusercontent.com/33105890/231858225-9d7cdd1e-5c0d-4481-8da3-0f6a39d96c58.mov
> feat(passport): apple email in dropdown

- apps/passport/app/components/connect-button/AuthButton.tsx
Doesn't shrink pfp for continue with button. Also truncates text on overflow (text-ellipsis)
- Closes #2106 
Visual changes were tested in browser on localhost
> fix(passport): truncate text for 'continue-with' button

- apps/passport/app/routes/index.tsx
- apps/passport/app/routes/settings.tsx
Going to Passport Settings directly by entering the URL in the browser, after just being signed out of a third part app, would cause the "Continue with" screen to be shown to log into Passport with. This would only happen on the first visit to Passport Settings, but not for the subequent ones. This fixes that.
- N/A
While being logged on to Passport Settings, log on to Profile and sign out. Then go to Passport Settings from the URL bar.
> fix(passport): Corrects Passport Settings redirection bug

- apps/passport/app/routes/authorize.tsx
The user-submission from the authorization screen (with both `email` and `connected_addresses` scope values) was overriding the object being sent with the `connected_addresses` property, overwriting the object that already had the submission for the `email` scope value.
- Closes #2132
Craft request with `email` and `connected_addresses` and ensure both claims are present in ID token.
> fix(passport): Fixed issue with submitted personaData

- apps/passport/app/routes/authorize.tsx
- packages/security/persona.ts
- packages/types/application.ts
- platform/access/src/jsonrpc/methods/exchangeToken.ts
- platform/access/src/jsonrpc/methods/getUserInfo.ts
Backend now supports submitting value of `AuthorizationControlSelect.ALL` for the `connected_addresses` property of `personaData`. 
- Closes #2129
1. Locally forced value of `connected_addresses` to be `AuthorizationControlSelection.ALL` in line 412 of authorize.tsx.
2. Crafted `/authorize` call with `connected_addresses` scope value and exchanged resulting code for access token. Verified response from `/userinfo` with given access token contained all addresses.
3. Added a new connected address and repeated the `/userinfo` verification in step 2. Disconnected an address and repeated the same.
> fix(passport): Support submitting connected address selection to ALL

- packages/security/persona.ts
Creates a unified Edge tag for nodes referencing other nodes. This will now be shared for personaData references as well as references to nodes in Console (eg. #1915)
N/A
N/A
> chore(passport): Unify tag naming for node references

- platform/access/src/jwk.ts
Removes JSON parsing from retrieval of env var value for SECRET_JWK_CURRENT_KID
N/A
Manual deploy to dev and log in to passport.
> fix(access): Remove JSON.parse from env var retrieval.

- docs/reference/passport-api.md
- packages/security/persona.ts
NOTE: This is a breaking change for the `connected_accounts` scope response schema. 
Rename `alias` to `identifier` in `connected_accounts` scope response.
Update docs to reflect the same.
- Closes #2161
Created new authorization request containing `connected_accounts` scope, and authorized all addresses. Checked ID token and content of `/userinfo` endpoint to verify new name for the property (`identifier`, not `alias`)
> chore(passport) Rename `alias` to `identifier` in `connected_accounts` scope response.

- packages/design-system/src/atoms/email/EmailSelect.stories.tsx
- packages/design-system/src/atoms/email/EmailSelect.tsx
> fix(passport): If name of email is the same for two types of email addresses they both look selected

- docs/reference/galaxy-api.md
This pull request corrects a minor typo in the documentation. The sentence in question originally read:
"This is the API Key that can be found in the dashboard of ***you*** [Console](../platform/console/) App..."
I have made a change to correct the typo and the sentence now reads:
"This is the API Key that can be found in the dashboard of your [Console](../platform/console/) App..."
> fix(docs): Correct typo in galaxy api

- packages/security/persona.ts
`connected_accounts` scope claims had different shapes, depending on if the user-selection was ALL or invididual accounts. `{ type, alias }` vs `{ identifier, alias }`. This makes the shape consistent to `{ identifier, alias }`
- N/A
- Test `/userinfo` after authz with `connected_accounts` with selection of ALL
- Test `/userinfo` after authz with `connected_accounts` with selection of individual accounts.
Both produced the same output shape.
> fix(passport): Makes `connected_accounts` claims consistently shaped

- apps/passport/app/routes/authenticate/$clientId.tsx
- apps/passport/app/routes/authenticate/$clientId/account.tsx
- apps/passport/app/routes/signout.tsx
- apps/passport/app/session.server.ts
- platform/access/src/jsonrpc/methods/revokeAppAuthorization.ts
- platform/account/src/jsonrpc/methods/deleteAccountNode.ts
- platform/address/src/jsonrpc/methods/deleteAddressNode.ts
- platform/edges/src/db/remove.ts
- platform/edges/src/jsonrpc/methods/deleteNode.ts
- platform/edges/src/jsonrpc/router.ts
- platform/starbase/src/jsonrpc/methods/deleteApp.ts
- Adds functionality to delete nodes in edges database.
- Adds node-deletion for account disconnect, app authz revocation and identity delete.
- Fixes issue with OG MetaFunction that was causing errors
- Addresses session invalidation after identity delete.
- Closes #2216
- Multiple passes through account and identity deletion. Same with application authz revocation.
- Refreshing "Continue with" screen after identity deletion.
> fix(platform): Delete node and session bugfixes after identity delete.

- apps/passport/app/routes/connect/$address/sign.tsx
- apps/passport/app/utils/authenticate.server.ts
---
A wallet account that is already connected should redirect back properly.
- Closes #2258
Also, confirmed it doesn't prematurely redirect back to example-nextjs
application.
> fix(passport): fix redirect URL when the wallet account is already connected

- platform/galaxy/src/schema/resolvers/address.ts
Fix 4337 data validation logic, now that the structure of persona data for `erc_4337` has changed.
- N/A
Tested interactively through NextAuthjs example app.
> fix(galaxy): Fix 4337 data validation logic

- apps/passport/app/routes/settings.tsx
Fix for app data error, causing Passport Settings not to load. This swallows the app-specific error and allows the user to recover.
- N/A
Deployed to dev where my user couldn't log on to Passport settings before this fix due to error. No error after fix.
> fix(passport): App data error in Passport settings

- apps/console/app/components/DeleteAppModal/DeleteAppModal.tsx
- apps/console/app/root.tsx
- apps/console/app/routes/apps/$clientId/auth.tsx
- apps/console/app/routes/apps/delete.tsx
- apps/console/app/types.ts
- platform/starbase/src/jsonrpc/methods/createCustomDomain.ts
- platform/starbase/src/jsonrpc/methods/deleteApp.ts
- platform/starbase/src/jsonrpc/methods/deleteCustomDomain.ts
- platform/starbase/src/jsonrpc/methods/getCustomDomain.ts
- platform/starbase/src/jsonrpc/validators/app.ts
- platform/starbase/src/jsonrpc/validators/customdomain.ts
- platform/starbase/src/nodes/application.ts
- platform/starbase/src/types.ts
The delete application modal displays a message that application has a custom
domain configured.
- Closes #2348
> feat(console): delete app modal checks custom domain config

- apps/passport/app/routes/authenticate/$clientId/index.tsx
- packages/design-system/src/atoms/buttons/connect-button/ConnectButton.tsx
Disables "disconnect" button when user is prompted to sing a message with wallet.
- Closes #2288 
1. Goto passport authn page
2. Select the option 'Connect with Wallet'
3. Select 'MetaMask' in the Connect Wallet-pop up
4. Connect a wallet and once connected click the 'Continue with <wallet_address>' button
5. Once the 'MetaMask Notification' window is displayed, try disconnecting the wallet and click 'Sign' on the MetaMask notification window.
> fix(passport): User able to disconnect the wallet and still sign in using the earlier triggered MetaMask notification

- packages/design-system/src/templates/authentication/Authentication.tsx
Returns Loading component back when loggin-in with non-blockchain oauth providers.
- Closes #2395
Was trying to log in with all providers in passport
> fix(passport): loading transition not shown when logging in with social

- packages/design-system/src/templates/authorization/Authorization.tsx
Turn connected accounts scope yellow when user needs to take action
- Closes #2411
Locally
> fix(passport): connected accounts scope is not yellow when user needs to take action 

- apps/passport/app/routes/settings.tsx
- apps/passport/app/routes/settings/applications/$clientId/index.tsx
- apps/passport/app/utils/authorize.server.ts
- packages/security/persona.ts
- platform/address/src/constants.ts
- platform/address/src/jsonrpc/methods/getAddressProfile.ts
- platform/address/src/jsonrpc/router.ts
- platform/address/src/nodes/contract.ts
- platform/edges/src/db/index.ts
- platform/edges/src/db/select.ts
- platform/edges/src/jsonrpc/methods/findNode.ts
- platform/edges/src/jsonrpc/router.ts
- platform/starbase/src/jsonrpc/methods/getAppPublicProps.ts
- platform/starbase/src/jsonrpc/router.ts
Adds batch interfaces and leverages them for specific "hot paths". The following now have batch variants that take an array of the same type as the non-batch variant.
- Address worker's `getAddressProfile()`
- Edge worker's `findNode()`
- Starbase worker's `getAppPublicProps()`
To get around our previous design choice of having an `AddressURN` be needed for the construction of the Address client, this also introduces a no-op placeholder AddressURN that can be used to initalize a client, so that the batch interfaces (with multiple AddressURNs) can be leveraged.
Also removes ENS lookups for smart contract wallets, due to the worker subrequest multiplication for contract addresses.
Note: `getAuthorizedAppScopes()` will get addressed as part of bigger effort under #2013 
- Closes #2215
- …
> chore(platform): Extend worker interfaces for batch operations

- apps/console/app/routes/apps/$clientId/designer.beta.tsx
- apps/passport/app/routes/authenticate/$clientId/email/index.tsx
- apps/passport/app/routes/authenticate/$clientId/email/verify.tsx
- apps/passport/app/utils/emailOTP.ts
- packages/design-system/src/atoms/buttons/Button.tsx
- packages/design-system/src/atoms/info/Info.tsx
- packages/design-system/src/templates/authorization/Authorization.tsx
Fix for email OTP screen. Now  not new OTP isn't being sent while refreshing the page on `/email/verify` route. All OTPs are being sent only while clicking buttons and first OTP is being sent while clicking `Send Code` button in `/email` route.
Also introduces minor style fixes in passport
- Closes #2293
Straightforward - go to `authenticate/passport/email` route, enter email and click `Send Code` - see the logs from platform workers.
Then under `verify` route try refreshing and see in logs that it does nothing. Try to issue 5 OTP within 5 minutes and then issue another one
Both pages - `authenticate/passport/email` and `authenticate/passport/email/verify` should show an error
> fix(passport): Refreshing the OTP submission page (with 30 secs interval) generates a new OTP and is shared to related email address

- apps/passport/app/root.tsx
- apps/passport/app/routes/authenticate/$clientId/index.tsx
- apps/passport/app/routes/settings.tsx
- apps/passport/app/session.server.ts
When there's already a session app will navigate user to the root loader to then redirect them to settings in passport
- Closes #2422
as described in issue
> fix(passport): authn screen becomes a dead-end when trying to sing-in with wallet when already signed-in

- apps/passport/app/root.tsx
- apps/passport/app/routes/authenticate/$clientId.tsx
- apps/passport/app/routes/authenticate/$clientId/email/verify.tsx
- apps/passport/app/routes/authenticate/$clientId/index.tsx
- apps/passport/app/routes/connect/$address/sign.tsx
- apps/passport/app/routes/settings/applications/$clientId/index.tsx
- apps/passport/app/session.server.ts
- apps/passport/bindings.d.ts
- apps/passport/server.ts
- packages/design-system/src/molecules/loader/Loader.tsx
- packages/platform-middleware/trace.ts
App's favicon on now displayed on the MetaMask Notification window
Loader in passport now reflects colours that were set in designer for specific app
Fixes bugs with redirects in passport which were not indicated in any other issues, stable temporary solution for `/sign` route when there's an error occurs. Solves issue with `/authenticate` route to not redirect to `/settings/dashboard` logged-in users.
Fetches appProps from starbase before loading context and puts it in the context object.
- Closes #2406
- Closes #2392 
Go to authn screen and pop-up metamask window to sign a message. Under custom domain or just with clientId for the specific app.
> fix(passport): displaying app's favicon in custom domain

- apps/passport/app/routes/authenticate/$clientId/index.tsx
- apps/passport/app/routes/connect/$address/sign.tsx
- apps/passport/app/routes/connect/email/otp.ts
- apps/passport/app/utils/emailOTP.ts
Prevents logging-in when already logged-in
1. Open `authenticate/passport` in 2 different tabs
2. Log in from one
3. Try to log in with wallet or get email OTP from second one
> fix(passport): logging-in is prevented when already logged-in

- apps/passport/app/root.tsx
There're two separate calls to starbase in passport now:
1. For custom domain appProps are being fetched in `server.ts`.
2. For all other apps without custom domain appProps are being fetched/set in `root.tsx` in `Passport`
Please note that call to starbase happens only once - for custom domains in `server.ts`, for all other apps - in `root.tsx`
Tested locally on `Passport`, `Console` and `Profile`
Deployed to dev and tested there on these three apps as well.
> fix(passport): set app name with no custom domain

- apps/console/app/routes/__layout/gnillib/details.tsx
- apps/passport/app/routes/settings/accounts/references.tsx
- platform/account/src/jsonrpc/methods/stripePaymentData.ts
- platform/address/src/jsonrpc/methods/getAddressReferenceTypes.ts
- Added edge Account -> Address to represent billing e-mail address associated to an account
- Added checks when deleting addresses in passport
- Closes #2402 
1. Add e-mail to billing
2. Go to passport
3. Try to delete account
4. Go back to console
5. Update address
6. Go back to passport
7. Try to delete
> chore(console): Add billing email selection dropdown

- apps/console/app/routes/__layout/gnillib/index.tsx
- apps/console/app/routes/__layout/gnillib/portal.tsx
- apps/console/app/routes/__layout/gnillib/webhook.tsx
- apps/console/app/routes/apps/$clientId/gnillib.tsx
- apps/console/app/services/billing/stripe.ts
- apps/console/bindings.d.ts
- apps/console/wrangler.toml
- packages/types/email.ts
- packages/types/index.ts
- platform/account/src/jsonrpc/methods/getEntitlements.ts
- platform/account/src/jsonrpc/router.ts
- platform/address/src/jsonrpc/methods/sendReconciliationNotificationMethod.ts
- platform/address/src/jsonrpc/router.ts
- platform/email/emailTemplate.ts
- platform/email/src/emailFunctions.ts
- platform/email/src/jsonrpc/methods/sendReconciliationNotification.ts
- platform/email/src/jsonrpc/router.ts
- platform/starbase/src/jsonrpc/methods/reconcileAppSubscriptions.ts
- platform/starbase/src/jsonrpc/methods/setAppPlan.ts
- platform/starbase/src/jsonrpc/router.ts
- platform/starbase/src/nodes/application.ts
- Added Invoices to billing screen
- Added reconciliation function for automagically downgrading apps if entitlements get removed through Stripe subscription
- Added two new e-mail templates for reconciliation (billing + dev)
- Added Portal endpoint for redirecting users to their Stripe Customer Portal
- Parametrized getEntitlements to be able to be used from public webhook
- 
- Closes #2404 
- Pause / unpause to be handled at a later date
- Did some small local testing, would need to do additional testing in dev
> feat(console): Billing and Invoicing - Invoice and payments integration

- apps/console/app/root.tsx
- apps/passport/app/root.tsx
- PostHog fails and crashes the entire passport / console app. Wrapped in try catch until handled.
- Deployed to dev
- Completed flow
> fix(posthog): wrap posthog init in try catch

- apps/console/app/routes/apps/$clientId/team.tsx
- apps/passport/app/routes/connect/email/otp.ts
- Added .toLowerCase to e-mail input when authenticating so that we get the same AddressURN regardless of casing
- Added defaultValue to Team Email Dropdown
- Went through a login flow and connect account flow
- Looked at team email dropdown
> fix(various): Email AddressURN and Team Email

- apps/passport/app/routes/authenticate/$clientId/email/index.tsx
Disables "Send Code" button in passport when OTP is being sent
locally
> fix(passport): disable send code button when code sent

- packages/design-system/src/helpers/get-text-color.ts
- Added hardcoded value for `indigo-500` background
- Wasn't able to reproduce Authorization height & dev is down for testing
- Closes #2450 
Visual
> fix(passport): Style Fixes

- platform/account/wrangler.toml
Removing the v2 DO migration for IdentityGroup as it was conflicting with v3 and preventing deploys to the upper environments.
- N/A
Manual deploy to dev and next, with no failures/conflicts.
> fix(account): Removing the v2 DO migration for IdentityGroup

- apps/console/app/components/IconPicker/index.tsx
- apps/console/app/routes/apps/$clientId/designer.tsx
- Added a new image variant in cloudflare: PassportAppCover
- Hooked variant to designer screen
- Closes #2525 
- Upload test cover from Ondrej (870x1306), doesn't get downscaled, uses new variant
- Uploded app icon, uses old default ('public') variant
- Maybe we'll need to step away from this variant model and go towards a model closer to https://developers.cloudflare.com/images/cloudflare-images/transform/flexible-variants/ but that needs to be investigated, what the pros and cons are.
> fix(console): Screen side image gets downscaled

- platform/edges/src/jsonrpc/methods/deleteNode.ts
Removing check that no longer works as intended, due to CF backend service changes. `result[x].meta.changes` no longer returns number of rows affected.
This builds on top of the previous functional PR to add the missing `await`.
- Closes #2323
- Closes #2178
Setup: Create identities, add accounts.
- Delete identity and recreate to ensure it's brand new
- Delete non-primary connected account and make sure it can be reconnected.
- Change the primary state on an account and try the cases above.
> fix(edges): Remove now-broken validation check

- platform/starbase/src/jsonrpc/methods/deleteApp.ts
`deleteApp()` was removing the app edge, but was not also removing the edge references that are used to associate the dev email to the app. This fixes the scenario.
- Closes #2480
1. Create app in Console
2. Associate a dev email in Team and Contacts
3. Go back to dashboard and delete app.
> fix(console): Remove reference edges before removing app node

- apps/console/app/entry.server.tsx
Introduced a more specific entry for the iFrame src for typeform
- Closes #2587 
- Works on my machine
> fix(Console): Typeform loading blocked

- platform/address/src/jsonrpc/methods/getAddressURNForEmail.ts
- platform/edges/src/db/select.ts
Corrects condition in rare billing email assignment scenario where a lookup of an urn by email address was returning (validly) multiple nodes, and we were treating that as an error.
- N/A
- Reproduced the issue before deploy and was unable to reproduce after deploy.
- Quick regression test for authorization details - focusing on connected accounts that use some of the same inner method as the ones that had to be tweaked as part of the fix.
> fix(core): Fix multi-node query method and rare billing email assignment.

- apps/console/app/root.tsx
- apps/console/app/routes/__layout/billing/webhook.tsx
- apps/console/app/routes/__layout/spuorg/$groupID/invite.tsx
- apps/console/app/routes/apps/delete.tsx
- apps/console/app/routes/apps/new.tsx
- apps/passport/app/root.tsx
- apps/passport/app/routes/authorize.tsx
- apps/passport/app/routes/settings.tsx
- apps/passport/app/routes/settings/accounts/rename.tsx
- apps/passport/app/routes/settings/advanced.tsx
- apps/passport/app/routes/settings/applications/$clientId/revoke.tsx
- packages/utils/analytics.ts
- platform/account/src/jsonrpc/methods/resolveIdentity.ts
- platform/authorization/src/jsonrpc/methods/authorize.ts
- platform/authorization/src/jsonrpc/methods/exchangeToken.ts
- platform/authorization/src/jsonrpc/methods/revokeAppAuthorization.ts
- platform/identity/src/jsonrpc/methods/identity-groups/createIdentityGroup.ts
- platform/identity/src/jsonrpc/methods/identity-groups/inviteIdentityGroupMember.ts
- platform/starbase/src/jsonrpc/methods/createApp.ts
- platform/starbase/src/jsonrpc/methods/deleteApp.ts
- platform/starbase/src/jsonrpc/methods/publishApp.ts
- platform/starbase/src/jsonrpc/methods/setAppPlan.ts
Creates tracking for groups' and apps' events for future metrics.
- Closes #2608
All events were tested locally.
> feat(analytics): track metrics for apps and groups as for users

- apps/passport/app/root.tsx
Tweaks the checking of the conditions when authorizing internal apps.
- N/A
Log in to passport and notice no more errors saying `Could not return properties for a published application with Client ID: passport` or `console`
> fix(passport): Root loader error check refinement

- apps/console/app/routes/apps/$clientId/designer.tsx
- packages/design-system/src/helpers/get-provider-icons.ts
- packages/design-system/src/templates/authentication/Authentication.tsx
- platform/starbase/src/jsonrpc/validators/app.ts
Adds passkeys to Designer.
- Closes #2665
In designer: 
- Authentication screen preview has passkeys as an option, rendered correctly for light and dark mode
- In Login Provider Configuration, Passkeys is an option that can be reordered and enabled/disabled.
> chore(console): Adds webauthn/passkeys to Designer

- docs/platform/passport.md
- docs/troubleshooting/faq.md
Docs updates for passkeys
- Closes #2667
N/A
> docs: Docs updates for passkeys

- apps/passport/app/components/email/EmailPanel.tsx
- apps/passport/app/routes/authenticate/$clientId/email/index.tsx
- apps/passport/app/routes/authenticate/$clientId/email/verify.tsx
- packages/design-system/src/molecules/email-otp-validator/EmailOTPValidator.tsx
- Removed flexor element
- Updated layout to be a simple flex col
- Fixed email overflow bug
- Closes #2704 
- There are still zooming in issues, unrelated to this bug / fix, when moving from one screen to another. This requires additional investigation and perhaps costly fixes. 
Deployed to dev and did the flow with my phone.
> fix(passport): "Continue with email" submission button below fold on mobile

- apps/console/app/routes/apps/$clientId/designer.tsx
- Limited provider list height
- Added scroll to provider list section
- Closes #2713
> fix(console): Designer provider list buttons not visible by default

- docs/platform/console/blockchain.md
- docs/platform/console/dashboard.md
- docs/platform/console/oauth.md
- docs/platform/passport.md
- docs/reference/galaxy-api.md
- docs/troubleshooting/faq.md
> chore: fix typos

- apps/console/app/routes/groups.enroll.$groupID.$invitationCode.tsx
- apps/console/app/routes/onboarding.tsx
- apps/console/app/routes/onboarding/index.tsx
- platform/identity/src/jsonrpc/methods/identity-groups/createIdentityGroup.ts
- platform/identity/src/jsonrpc/router.ts
- Enabled group (team) creation flow;
- Added a new group (team) enrollment flow;
These two additions build on what was already existing in the onboarding flow with minimal possible changes. Currently there are some code smells that might prove problematic in the future but these belong to another PR.
- Enrollment now redirects to onboarding instead of group;
- Onboarding can be skipped after filling in billing details.
- Closes #2645 
1. Go to console
2. Get redirected to passport
3. Connect using a new account
4. Select single dev
5. Fill in app details
6. Continue to app
1. Go to console
2. Get redirected to passport
3. Connect using a new accont
4. Select team
5. Fill in group name & other form items
7. Continue to group
1. In the previously created group invite a new member
2. As the …
> chore(console): Onboarding flow for teams

- apps/passport/app/routes/connect/email/otp.ts
The [`origin`](https://developer.mozilla.org/en-US/docs/Web/API/URL/origin) property is the one that has all components to construct a proper URL.
> fix(passport): get `origin` property from the request URL

- apps/console/app/components/IconPicker/index.tsx
- apps/console/app/routes/apps/$clientId/auth.tsx
- apps/console/app/routes/apps/$clientId/designer.tsx
- apps/console/app/utils/formCFImages.client.ts
- apps/console/server.ts
- apps/profile/app/entry.server.tsx
- apps/profile/app/routes/account/profile.tsx
- apps/profile/app/utils/formCFImages.client.ts
- apps/profile/server.ts
- platform/images/src/jsonrpc/methods/delete.ts
- platform/images/src/jsonrpc/router.ts
- Closes #2549 
- Visual check in CF image bucket
> chore(platform): delete old images on upload of new ones

- platform/email/emailTemplate.ts
Two transactional emails -- purchase successful and purchase failure -- referred to "the Rollup ID". This removes the article "the" so that branding is more consistent.
- NA
NA
- [na] I have tested my code (manually and/or automated if applicable)
- [na] I have updated the documentation (if necessary)
> fix(email): Remove 'the' from some transactional emails

- platform/galaxy/src/index.ts
- platform/galaxy/src/schema/resolvers/authorization.ts
- platform/galaxy/src/schema/types/authorization.ts
- platform/galaxy/src/schema/types/common.ts
- platform/starbase/src/jsonrpc/router.ts
Implements Galaxy operation to retrieve authorized identities for an application, identified through the API key.
Returns `identityURN`, `name` and `imageURL` for each entry.
Note: connected accounts won't be returned as those can be retrieved proactively on a per-user basis through the standard `/userinfo` endpoint, or reactively per-change-event through future work done under #2621
- Closes #2716
- Make graphql call to `getAuthorizedIdentities()` with a galaxy API key issued for an app with authorized users. 
- Validate same users appear as the ones in users listing in Console for same app
> chore(galaxy): Operation for retrieving authorized identities

- platform/galaxy/src/schema/resolvers/authorization.ts
Resolver validation failures on `getAuthorizedIdentities` resolver now produce a user-visible error.
- Closes #2833
- Use a pagination input outside the valid range, eg. limit: 51
> fix(galaxy): Produces error when user listing resolver fails validation.

- packages/types/headers.ts
- platform/emaildistributor/src/index.ts
- platform/emailinbounder/.dev.vars.example
- platform/emailinbounder/src/index.ts
- platform/emailinbounder/wrangler.current.toml
- platform/emailinbounder/wrangler.dev.toml
- platform/emailinbounder/wrangler.next.toml
- platform/emailinbounder/wrangler.toml
Prevents duplicate relay emails from being sent, when there are multiple relay addresses in to/cc fields.
Also moves env var from being considered a secret to a regular env var.
- Closes #2840
Send email to at least 2 relay addresses and ensure only one copy is received on each target unmasked address.
> fix(emailinbounder): Fixes email duplication in relay
